// 人生之书：访谈话术库
// 纯数据，机器可检查。AI 扮演晚辈陪老人聊天，边聊边把人生整理成传记。
// 铁律：
//   1. 问题必须具体到生活细节，能从老人的上一句话里延伸，绝不照着清单念。
//   2. 不查户口：不直接索要姓名/年龄/职业/住址/身份证，这些只从聊天里自然浮现。
//   3. 老人拒绝、沉默、重复，都是有效信息，不纠正、不打断、不追问。
//   4. 所有话都要能对着老人念出口，用"您""咱""那会儿""啥"。

export const bank = {
  version: '1.0',

  // 人生阶段。id 固定 7 个，顺序不变。
  stages: [
    { id: 'childhood', name: '童年', yearsHint: '大约 0 到 14 岁', intro: '从会记事儿说起，讲小时候的吃穿住、玩和亲人。' },
    { id: 'schooling', name: '上学', yearsHint: '大约 7 到 20 岁', intro: '上学念书的年月，学堂、老师、同学、放学的路。' },
    { id: 'youth', name: '青年谋生', yearsHint: '大约 15 到 30 岁', intro: '头一回干活挣钱，学手艺、进厂、当兵、出远门。' },
    { id: 'family', name: '成家', yearsHint: '大约 20 到 40 岁', intro: '结婚成家、生儿育女，安家落户的头几年。' },
    { id: 'midlife', name: '中年', yearsHint: '大约 40 到 60 岁', intro: '上有老下有小的年月，最忙最累也最扛事。' },
    { id: 'later', name: '晚年', yearsHint: '60 岁往后', intro: '退休以后的日月，如今的日子和想说的话。' },
    { id: 'anytime', name: '不分年纪', yearsHint: '任何时候都能问', intro: '这些话题不挑年纪，聊到哪儿都能接上。' }
  ],

  // 主题。用于保证访谈覆盖面，别一直问吃饭。
  topics: [
    { id: 'food', name: '吃食' },
    { id: 'clothes', name: '穿戴' },
    { id: 'housing', name: '住处' },
    { id: 'work', name: '干活' },
    { id: 'school', name: '上学' },
    { id: 'play', name: '玩' },
    { id: 'kin', name: '亲人' },
    { id: 'marriage', name: '婚嫁' },
    { id: 'raising', name: '生养' },
    { id: 'craft', name: '手艺' },
    { id: 'money', name: '钱' },
    { id: 'travel', name: '走路远行' },
    { id: 'illness', name: '生病' },
    { id: 'festival', name: '节令' },
    { id: 'objects', name: '老物件' },
    { id: 'senses', name: '声音气味' },
    { id: 'name', name: '名字来历' },
    { id: 'hardship', name: '最难的时候' },
    { id: 'joy', name: '最高兴的时候' },
    { id: 'legacy', name: '说给后人听' },
    { id: 'letters', name: '信' },
    { id: 'value', name: '做人的道理' }
  ],

  questions: [
    // ---------- 童年（31） ----------
    { id: 'food-childhood-01', stage: 'childhood', topic: 'food', text: '您小时候，家里最常吃的是啥饭？', kind: 'opener', weight: 4, captures: ['food'], sensitivity: 0, followUps: [ { when: ['玉米', '苞米', '粗粮'], ask: '那细粮是留着啥时候吃？' }, { when: [], ask: '这饭是谁做的？' } ] },
    { id: 'food-childhood-02', stage: 'childhood', topic: 'food', text: '小时候家里贴饼子，还是蒸窝头？', kind: 'detail', weight: 3, captures: ['food'], sensitivity: 0, followUps: [ { when: ['窝头'], ask: '那窝头是啥面蒸的？' } ] },
    { id: 'housing-childhood-01', stage: 'childhood', topic: 'housing', text: '您小时候睡的是炕还是床？', kind: 'sensory', weight: 3, captures: ['home'], sensitivity: 0, followUps: [ { when: ['炕'], ask: '冬天烧炕不？' } ] },
    { id: 'play-childhood-01', stage: 'childhood', topic: 'play', text: '您小时候最爱玩啥？', kind: 'opener', weight: 4, captures: ['joy'], sensitivity: 0, followUps: [ { when: ['弹球', '玻璃球'], ask: '玻璃球是咋赢来的？' } ] },
    { id: 'food-childhood-03', stage: 'childhood', topic: 'food', text: '小时候能吃上白面馒头不？', kind: 'detail', weight: 3, captures: ['food'], sensitivity: 0, followUps: [ { when: ['能'], ask: '那馒头是谁蒸的？' }, { when: ['不能', '吃不上'], ask: '那平时吃啥？' } ] },
    { id: 'kin-childhood-01', stage: 'childhood', topic: 'kin', text: '您小时候，家里谁做饭？', kind: 'detail', weight: 3, captures: ['parents', 'food'], sensitivity: 0, followUps: [ { when: [], ask: '她做饭有啥拿手的？' } ] },
    { id: 'senses-childhood-01', stage: 'childhood', topic: 'senses', text: '冬天早起，被窝里冷不冷？', kind: 'sensory', weight: 3, captures: ['home'], sensitivity: 0, followUps: [ { when: ['冷'], ask: '那您咋起来？' } ] },
    { id: 'senses-childhood-02', stage: 'childhood', topic: 'senses', text: '您小时候，闻到过啥特别香的东西？', kind: 'sensory', weight: 3, captures: ['food'], sensitivity: 0, followUps: [ { when: [], ask: '那香味儿是哪儿来的？' } ] },
    { id: 'objects-childhood-01', stage: 'childhood', topic: 'objects', text: '您小时候，家里墙上贴的是啥画？', kind: 'object', weight: 3, captures: ['heirloom', 'home'], sensitivity: 0, followUps: [ { when: [], ask: '那画上画的是啥？' } ] },
    { id: 'food-childhood-04', stage: 'childhood', topic: 'food', text: '过年才能吃上的东西，是啥？', kind: 'detail', weight: 3, captures: ['festival', 'food'], sensitivity: 0, followUps: [ { when: [], ask: '那东西啥味儿？' } ] },
    { id: 'kin-childhood-02', stage: 'childhood', topic: 'kin', text: '您小时候，家里谁最疼您？', kind: 'relation', weight: 4, captures: ['importantPerson'], sensitivity: 1, followUps: [ { when: [], ask: '她疼您，是咋个疼法？' } ] },
    { id: 'play-childhood-02', stage: 'childhood', topic: 'play', text: '您小时候会爬树不？', kind: 'detail', weight: 2, captures: ['joy'], sensitivity: 0, followUps: [ { when: ['会'], ask: '上树干啥去？' } ] },
    { id: 'kin-childhood-03', stage: 'childhood', topic: 'kin', text: '您小时候，大人打过您没有？', kind: 'detail', weight: 2, captures: ['parents'], sensitivity: 1, followUps: [ { when: ['打过'], ask: '是因为啥？' } ] },
    { id: 'food-childhood-05', stage: 'childhood', topic: 'food', text: '您小时候吃过榆钱不？', kind: 'detail', weight: 3, captures: ['food'], sensitivity: 0, followUps: [ { when: ['吃过'], ask: '那是啥味儿？' } ] },
    { id: 'play-childhood-03', stage: 'childhood', topic: 'play', text: '您小时候下河摸过鱼不？', kind: 'sensory', weight: 2, captures: ['joy'], sensitivity: 0, followUps: [ { when: ['摸过'], ask: '水凉不凉？' } ] },
    { id: 'housing-childhood-02', stage: 'childhood', topic: 'housing', text: '小时候家里点油灯，还是电灯？', kind: 'object', weight: 3, captures: ['home', 'heirloom'], sensitivity: 0, followUps: [ { when: ['油灯'], ask: '油灯是啥样儿的？' } ] },
    { id: 'kin-childhood-04', stage: 'childhood', topic: 'kin', text: '您爹年轻时候，是干啥的？', kind: 'relation', weight: 3, captures: ['parents'], sensitivity: 0, followUps: [ { when: [], ask: '他干活您跟着去过不？' } ] },
    { id: 'senses-childhood-03', stage: 'childhood', topic: 'senses', text: '夏天夜里热，您上哪儿睡？', kind: 'sensory', weight: 3, captures: ['home'], sensitivity: 0, followUps: [ { when: ['房顶', '院里'], ask: '躺那儿能看见星星不？' } ] },
    { id: 'food-childhood-06', stage: 'childhood', topic: 'food', text: '那会儿吃糖，吃的是啥糖？', kind: 'detail', weight: 2, captures: ['food'], sensitivity: 0, followUps: [ { when: ['水果糖'], ask: '一颗能含多久？' } ] },
    { id: 'clothes-childhood-01', stage: 'childhood', topic: 'clothes', text: '您小时候穿过打补丁的衣裳不？', kind: 'object', weight: 3, captures: ['clothes'], sensitivity: 0, followUps: [ { when: ['穿过'], ask: '补丁是谁补的？' } ] },
    { id: 'play-childhood-04', stage: 'childhood', topic: 'play', text: '冬天，你们小孩儿都玩啥？', kind: 'detail', weight: 2, captures: ['joy'], sensitivity: 0, followUps: [ { when: ['滑', '冰'], ask: '冰车是咋做的？' } ] },
    { id: 'senses-childhood-04', stage: 'childhood', topic: 'senses', text: '您小时候，最怕的是啥？', kind: 'sensory', weight: 2, captures: ['hardship'], sensitivity: 1, followUps: [ { when: [], ask: '怕的那阵子，谁陪着您？' } ] },
    { id: 'food-childhood-07', stage: 'childhood', topic: 'food', text: '家里来了客人，饭桌上多啥菜？', kind: 'detail', weight: 2, captures: ['food'], sensitivity: 0, followUps: [ { when: [], ask: '那菜您能上桌不？' } ] },
    { id: 'kin-childhood-05', stage: 'childhood', topic: 'kin', text: '您有几个兄弟姐妹？', kind: 'detail', weight: 3, captures: ['siblings'], sensitivity: 0, followUps: [ { when: [], ask: '您排行老几？' } ] },
    { id: 'senses-childhood-05', stage: 'childhood', topic: 'senses', text: '那会儿下雨，屋里漏雨不？', kind: 'sensory', weight: 3, captures: ['home'], sensitivity: 1, followUps: [ { when: ['漏'], ask: '漏雨的地儿，拿啥接？' } ] },
    { id: 'play-childhood-05', stage: 'childhood', topic: 'play', text: '您小时候玩过弹弓不？', kind: 'object', weight: 2, captures: ['joy'], sensitivity: 0, followUps: [ { when: ['玩过'], ask: '弹弓是谁给您做的？' } ] },
    { id: 'food-childhood-08', stage: 'childhood', topic: 'food', text: '小时候早上起来，喝粥还是喝糊糊？', kind: 'detail', weight: 3, captures: ['food'], sensitivity: 0, followUps: [ { when: [], ask: '碗里放糖不？' } ] },
    { id: 'kin-childhood-06', stage: 'childhood', topic: 'kin', text: '小时候睡觉，您挨着谁睡？', kind: 'relation', weight: 3, captures: ['importantPerson'], sensitivity: 1, followUps: [ { when: [], ask: '挨着睡，暖和吧？' } ] },
    { id: 'work-childhood-01', stage: 'childhood', topic: 'work', text: '您小时候，喂过猪没有？', kind: 'detail', weight: 2, captures: ['job'], sensitivity: 0, followUps: [ { when: ['喂过'], ask: '猪食是啥做的？' } ] },
    { id: 'value-childhood-01', stage: 'childhood', topic: 'kin', text: '您小时候，大人教的头一条道理是啥？', kind: 'value', weight: 3, captures: ['motto'], sensitivity: 0, followUps: [ { when: [], ask: '这话您还记得不？' } ] },
    { id: 'hardship-childhood-01', stage: 'childhood', topic: 'hardship', text: '您小时候，赶上过吃不饱的年头不？', kind: 'detail', weight: 4, captures: ['hardship'], sensitivity: 3, followUps: [ { when: ['赶上过'], ask: '那些年，家里都吃啥？' } ] },
    // ---------- 上学（20） ----------
    { id: 'schooling-school-01', stage: 'schooling', topic: 'school', text: '您上学那会儿，学校离家远不远？', kind: 'detail', weight: 4, captures: ['school'], sensitivity: 0, followUps: [ { when: ['远', '走'], ask: '走一趟得多久？' } ] },
    { id: 'schooling-school-02', stage: 'schooling', topic: 'school', text: '上学走的是土路，还是石头路？', kind: 'detail', weight: 3, captures: ['school', 'travel'], sensitivity: 0, followUps: [ { when: [], ask: '下雨天路好走不？' } ] },
    { id: 'schooling-school-03', stage: 'schooling', topic: 'school', text: '那会儿上学，中午饭咋解决？', kind: 'detail', weight: 3, captures: ['school', 'food'], sensitivity: 0, followUps: [ { when: ['带'], ask: '带的是啥干粮？' } ] },
    { id: 'schooling-school-04', stage: 'schooling', topic: 'school', text: '学堂里用的桌子，是啥样儿的？', kind: 'object', weight: 3, captures: ['school', 'heirloom'], sensitivity: 0, followUps: [ { when: ['土', '台'], ask: '写字硌不硌手？' } ] },
    { id: 'schooling-school-05', stage: 'schooling', topic: 'school', text: '您的老师，是男的还是女的？', kind: 'relation', weight: 3, captures: ['school'], sensitivity: 0, followUps: [ { when: [], ask: '那位老师脾气咋样？' } ] },
    { id: 'schooling-school-06', stage: 'schooling', topic: 'school', text: '老师打过手心没有？', kind: 'detail', weight: 2, captures: ['school'], sensitivity: 1, followUps: [ { when: ['打过'], ask: '为啥打的？' } ] },
    { id: 'schooling-school-07', stage: 'schooling', topic: 'school', text: '那会儿写字，用啥写？', kind: 'object', weight: 3, captures: ['school', 'heirloom'], sensitivity: 0, followUps: [ { when: ['石板'], ask: '石板是学校发的？' }, { when: ['毛笔'], ask: '墨是自己磨的？' } ] },
    { id: 'schooling-school-08', stage: 'schooling', topic: 'school', text: '您还记得头一篇课文不？', kind: 'detail', weight: 3, captures: ['school'], sensitivity: 0, followUps: [ { when: ['记得'], ask: '头一句是啥？' } ] },
    { id: 'schooling-school-09', stage: 'schooling', topic: 'school', text: '放学路上，您都干点啥？', kind: 'detail', weight: 3, captures: ['school', 'job'], sensitivity: 0, followUps: [ { when: ['拾', '柴'], ask: '拾柴是为了烧火做饭？' } ] },
    { id: 'schooling-school-10', stage: 'schooling', topic: 'school', text: '您那会儿，上了几年学？', kind: 'turning', weight: 4, captures: ['school'], sensitivity: 1, followUps: [ { when: ['没上', '不上了'], ask: '是咋没接着上的？' } ] },
    { id: 'schooling-school-11', stage: 'schooling', topic: 'school', text: '放下书本那天，您心里啥滋味？', kind: 'sensory', weight: 3, captures: ['school'], sensitivity: 2, followUps: [ { when: [], ask: '那天您回家，家里人说啥了？' } ] },
    { id: 'schooling-school-12', stage: 'schooling', topic: 'school', text: '那会儿学费，要交多少钱？', kind: 'detail', weight: 3, captures: ['school', 'money'], sensitivity: 0, followUps: [ { when: [], ask: '这钱家里咋攒出来的？' } ] },
    { id: 'schooling-play-01', stage: 'schooling', topic: 'play', text: '学校里课间，玩啥？', kind: 'detail', weight: 2, captures: ['joy'], sensitivity: 0, followUps: [ { when: [], ask: '下课钟一响，谁跑得最快？' } ] },
    { id: 'schooling-clothes-01', stage: 'schooling', topic: 'clothes', text: '上学头一天，您穿的是啥？', kind: 'detail', weight: 3, captures: ['clothes', 'school'], sensitivity: 0, followUps: [ { when: [], ask: '那衣裳是新的还是旧的？' } ] },
    { id: 'schooling-senses-01', stage: 'schooling', topic: 'senses', text: '冬天上学，手冻不冻？', kind: 'sensory', weight: 3, captures: ['school', 'illness'], sensitivity: 0, followUps: [ { when: ['冻'], ask: '冻了咋办？' } ] },
    { id: 'schooling-food-01', stage: 'schooling', topic: 'food', text: '学校里管饭不？', kind: 'detail', weight: 2, captures: ['school', 'food'], sensitivity: 0, followUps: [ { when: ['管'], ask: '吃的是啥饭？' } ] },
    { id: 'schooling-school-13', stage: 'schooling', topic: 'school', text: '您同桌是谁，还记得不？', kind: 'relation', weight: 3, captures: ['school'], sensitivity: 0, followUps: [ { when: ['记得'], ask: '那位同桌叫啥名儿？' } ] },
    { id: 'schooling-school-14', stage: 'schooling', topic: 'school', text: '上学路上，有条河不？', kind: 'detail', weight: 2, captures: ['school', 'travel'], sensitivity: 0, followUps: [ { when: ['有'], ask: '河上有没有桥？' } ] },
    { id: 'schooling-school-15', stage: 'schooling', topic: 'school', text: '那会儿念书的姑娘多不多？', kind: 'detail', weight: 3, captures: ['school'], sensitivity: 0, followUps: [ { when: ['不多'], ask: '为啥念书的姑娘少？' } ] },
    { id: 'schooling-school-16', stage: 'schooling', topic: 'school', text: '上学那会儿，一天上几节课？', kind: 'detail', weight: 2, captures: ['school'], sensitivity: 0, followUps: [ { when: [], ask: '哪节课最盼着上？' } ] },
    // ---------- 青年谋生（29） ----------
    { id: 'youth-work-01', stage: 'youth', topic: 'work', text: '您头一回干活，干的是啥？', kind: 'opener', weight: 5, captures: ['firstJob'], sensitivity: 0, followUps: [ { when: [], ask: '那活儿是咋学会的？' } ] },
    { id: 'youth-money-01', stage: 'youth', topic: 'money', text: '头一回挣的钱，您拿它买了啥？', kind: 'turning', weight: 4, captures: ['money', 'firstJob'], sensitivity: 0, followUps: [ { when: [], ask: '剩下的是咋花的？' } ] },
    { id: 'youth-work-02', stage: 'youth', topic: 'work', text: '那会儿干活，一天能挣几毛？', kind: 'detail', weight: 3, captures: ['money', 'job'], sensitivity: 0, followUps: [ { when: [], ask: '挣的钱够买啥？' } ] },
    { id: 'youth-craft-01', stage: 'youth', topic: 'craft', text: '您学手艺，是跟谁学的？', kind: 'detail', weight: 4, captures: ['craft'], sensitivity: 0, followUps: [ { when: [], ask: '师傅是啥脾气？' } ] },
    { id: 'youth-craft-02', stage: 'youth', topic: 'craft', text: '学手艺头一天，师傅让您干啥？', kind: 'detail', weight: 3, captures: ['craft'], sensitivity: 0, followUps: [ { when: [], ask: '您乐意干不？' } ] },
    { id: 'youth-work-03', stage: 'youth', topic: 'work', text: '干了一天活，手上起茧子不？', kind: 'sensory', weight: 3, captures: ['job'], sensitivity: 0, followUps: [ { when: ['起'], ask: '茧子长在哪个指头上？' } ] },
    { id: 'youth-work-04', stage: 'youth', topic: 'work', text: '那会儿干活，吃的是啥饭？', kind: 'detail', weight: 3, captures: ['food', 'job'], sensitivity: 0, followUps: [ { when: [], ask: '干活的人饭量大不？' } ] },
    { id: 'youth-travel-01', stage: 'youth', topic: 'travel', text: '您头一回进城，是啥时候？', kind: 'detail', weight: 4, captures: ['travel'], sensitivity: 0, followUps: [ { when: [], ask: '进城看见啥，最稀罕？' } ] },
    { id: 'youth-travel-02', stage: 'youth', topic: 'travel', text: '头一回坐火车，是去哪儿？', kind: 'detail', weight: 3, captures: ['travel'], sensitivity: 0, followUps: [ { when: [], ask: '火车是啥样儿的？' } ] },
    { id: 'youth-travel-03', stage: 'youth', topic: 'travel', text: '那会儿火车票，多少钱一张？', kind: 'detail', weight: 3, captures: ['travel', 'money'], sensitivity: 0, followUps: [ { when: [], ask: '谁给您买的票？' } ] },
    { id: 'youth-work-05', stage: 'youth', topic: 'work', text: '那会儿干活，您住在哪儿？', kind: 'detail', weight: 3, captures: ['home', 'job'], sensitivity: 0, followUps: [ { when: [], ask: '住的地儿挤不挤？' } ] },
    { id: 'youth-work-06', stage: 'youth', topic: 'work', text: '那会儿干活，起多早？', kind: 'detail', weight: 3, captures: ['job'], sensitivity: 0, followUps: [ { when: [], ask: '天还黑着不？' } ] },
    { id: 'youth-value-01', stage: 'youth', topic: 'work', text: '干活最累的时候，您心里想啥？', kind: 'value', weight: 3, captures: ['hardship'], sensitivity: 1, followUps: [ { when: [], ask: '有没有想撂挑子的时候？' } ] },
    { id: 'youth-military-01', stage: 'youth', topic: 'work', text: '您当过兵没有？', kind: 'turning', weight: 4, captures: ['military'], sensitivity: 0, followUps: [ { when: ['当过'], ask: '当兵头一天，干啥了？' } ] },
    { id: 'youth-factory-01', stage: 'youth', topic: 'senses', text: '头一回进车间，闻着啥味儿？', kind: 'sensory', weight: 3, captures: ['factory'], sensitivity: 0, followUps: [ { when: [], ask: '那味儿现在还记得不？' } ] },
    { id: 'youth-factory-02', stage: 'youth', topic: 'work', text: '那会儿上班，三班倒不？', kind: 'detail', weight: 3, captures: ['factory', 'job'], sensitivity: 0, followUps: [ { when: ['倒'], ask: '夜班困了咋办？' } ] },
    { id: 'youth-countryside-01', stage: 'youth', topic: 'work', text: '您下过乡没有？', kind: 'turning', weight: 4, captures: ['countryside'], sensitivity: 0, followUps: [ { when: ['下过'], ask: '在哪个村待的？' } ] },
    { id: 'youth-work-07', stage: 'youth', topic: 'work', text: '那会儿干活，您跟谁搭伴儿？', kind: 'relation', weight: 3, captures: ['importantPerson'], sensitivity: 0, followUps: [ { when: [], ask: '您俩谁干活麻利？' } ] },
    { id: 'youth-work-08', stage: 'youth', topic: 'work', text: '歇晌的时候，大伙儿唠啥？', kind: 'detail', weight: 2, captures: ['job'], sensitivity: 0, followUps: [ { when: [], ask: '您插得上话不？' } ] },
    { id: 'youth-clothes-01', stage: 'youth', topic: 'clothes', text: '那会儿您穿的是啥鞋？', kind: 'detail', weight: 3, captures: ['clothes'], sensitivity: 0, followUps: [ { when: ['布鞋'], ask: '布鞋是谁纳的底？' } ] },
    { id: 'youth-money-02', stage: 'youth', topic: 'money', text: '那会儿的粮票，是咋来的？', kind: 'object', weight: 3, captures: ['money', 'heirloom'], sensitivity: 0, followUps: [ { when: [], ask: '粮票一个月发多少？' } ] },
    { id: 'youth-work-09', stage: 'youth', topic: 'work', text: '您干过最重的活，是啥？', kind: 'sensory', weight: 3, captures: ['job', 'hardship'], sensitivity: 1, followUps: [ { when: [], ask: '那活干完，身上啥样？' } ] },
    { id: 'youth-travel-04', stage: 'youth', topic: 'travel', text: '那会儿出远门，靠啥走？', kind: 'detail', weight: 3, captures: ['travel'], sensitivity: 0, followUps: [ { when: ['走'], ask: '走几天能到？' } ] },
    { id: 'youth-turning-01', stage: 'youth', topic: 'value', text: '您年轻时候，自己拿过啥主意？', kind: 'turning', weight: 3, captures: ['importantYear'], sensitivity: 1, followUps: [ { when: [], ask: '那主意家里同意不？' } ] },
    { id: 'youth-value-02', stage: 'youth', topic: 'joy', text: '您年轻时候，最得意的一件事是啥？', kind: 'value', weight: 3, captures: ['joy'], sensitivity: 0, followUps: [ { when: [], ask: '得意了多久？' } ] },
    { id: 'youth-sensory-01', stage: 'youth', topic: 'hardship', text: '饿得最狠那回，您还记得不？', kind: 'sensory', weight: 3, captures: ['hardship'], sensitivity: 2, followUps: [ { when: [], ask: '那回是咋扛过去的？' } ] },
    { id: 'youth-object-01', stage: 'youth', topic: 'objects', text: '您攒钱买过啥大件没有？', kind: 'object', weight: 3, captures: ['money', 'heirloom'], sensitivity: 0, followUps: [ { when: ['自行车', '表', '缝纫机'], ask: '攒了多久？' } ] },
    { id: 'youth-sensory-02', stage: 'youth', topic: 'work', text: '那会儿下地，晌午头晒不晒？', kind: 'sensory', weight: 2, captures: ['job'], sensitivity: 0, followUps: [ { when: ['晒'], ask: '晒得皮疼不？' } ] },
    { id: 'youth-hardship-02', stage: 'youth', topic: 'hardship', text: '那几年吃不饱饭，您还记得不？', kind: 'detail', weight: 4, captures: ['hardship'], sensitivity: 3, followUps: [ { when: ['记得'], ask: '您要是愿意说，就说点。' } ] },
    // ---------- 成家（25） ----------
    { id: 'family-marriage-01', stage: 'family', topic: 'marriage', text: '您跟老伴儿，是咋认识的？', kind: 'opener', weight: 5, captures: ['marriage'], sensitivity: 0, followUps: [ { when: [], ask: '头一回见，是啥场景？' } ] },
    { id: 'family-marriage-02', stage: 'family', topic: 'marriage', text: '相亲那天，您穿的啥？', kind: 'detail', weight: 3, captures: ['marriage', 'clothes'], sensitivity: 0, followUps: [ { when: [], ask: '那衣裳是谁给置办的？' } ] },
    { id: 'family-marriage-03', stage: 'family', topic: 'marriage', text: '您俩头一回见面，说了啥？', kind: 'detail', weight: 3, captures: ['marriage'], sensitivity: 0, followUps: [ { when: [], ask: '那句话您还记得不？' } ] },
    { id: 'family-marriage-04', stage: 'family', topic: 'marriage', text: '结婚那天，下雨了没有？', kind: 'sensory', weight: 3, captures: ['marriage'], sensitivity: 0, followUps: [ { when: ['下'], ask: '雨里咋办的喜事？' } ] },
    { id: 'family-marriage-05', stage: 'family', topic: 'marriage', text: '那会儿结婚，家里给备了啥？', kind: 'object', weight: 3, captures: ['marriage', 'heirloom'], sensitivity: 1, followUps: [ { when: [], ask: '那床被子是啥面的？' } ] },
    { id: 'family-marriage-06', stage: 'family', topic: 'marriage', text: '结婚那天，摆了几桌酒？', kind: 'detail', weight: 2, captures: ['marriage'], sensitivity: 0, followUps: [ { when: ['没摆', '没办'], ask: '那喜事是咋办的？' } ] },
    { id: 'family-raising-01', stage: 'family', topic: 'raising', text: '头一个孩子，是在家生的吗？', kind: 'detail', weight: 3, captures: ['children'], sensitivity: 1, followUps: [ { when: ['家'], ask: '接生的是谁？' } ] },
    { id: 'family-raising-02', stage: 'family', topic: 'raising', text: '坐月子的时候，吃的是啥？', kind: 'detail', weight: 3, captures: ['children', 'food'], sensitivity: 1, followUps: [ { when: [], ask: '一天吃几个鸡蛋？' } ] },
    { id: 'family-raising-03', stage: 'family', topic: 'raising', text: '孩子夜里闹，您咋哄？', kind: 'detail', weight: 3, captures: ['children'], sensitivity: 0, followUps: [ { when: ['背'], ask: '背着走多久才睡？' } ] },
    { id: 'family-raising-04', stage: 'family', topic: 'raising', text: '您给孩子做过啥衣裳？', kind: 'detail', weight: 2, captures: ['clothes', 'children'], sensitivity: 0, followUps: [ { when: [], ask: '裁衣裳的布是哪儿来的？' } ] },
    { id: 'family-raising-05', stage: 'family', topic: 'raising', text: '孩子头一回会走，您还记得不？', kind: 'detail', weight: 3, captures: ['children'], sensitivity: 0, followUps: [ { when: ['记得'], ask: '头一步是咋迈的？' } ] },
    { id: 'family-money-01', stage: 'family', topic: 'money', text: '成家以后，您俩谁管钱？', kind: 'detail', weight: 3, captures: ['money', 'marriage'], sensitivity: 1, followUps: [ { when: [], ask: '钱匣子搁在哪儿？' } ] },
    { id: 'family-money-02', stage: 'family', topic: 'money', text: '那会儿一个月挣的钱，够花不？', kind: 'detail', weight: 3, captures: ['money'], sensitivity: 1, followUps: [ { when: ['不够'], ask: '不够了咋办？' } ] },
    { id: 'family-housing-01', stage: 'family', topic: 'housing', text: '结婚以后，住的是啥房子？', kind: 'detail', weight: 4, captures: ['home'], sensitivity: 0, followUps: [ { when: ['土'], ask: '土墙多厚？' } ] },
    { id: 'family-object-01', stage: 'family', topic: 'objects', text: '家里添过缝纫机没有？', kind: 'object', weight: 3, captures: ['heirloom'], sensitivity: 0, followUps: [ { when: ['添过'], ask: '是啥牌子？' } ] },
    { id: 'family-object-02', stage: 'family', topic: 'objects', text: '那台缝纫机，攒了多久买的？', kind: 'object', weight: 3, captures: ['heirloom', 'money'], sensitivity: 0, followUps: [ { when: [], ask: '买回来头一天，做了啥？' } ] },
    { id: 'family-object-03', stage: 'family', topic: 'objects', text: '那会儿家里有自行车不？', kind: 'object', weight: 3, captures: ['heirloom'], sensitivity: 0, followUps: [ { when: ['有'], ask: '是啥牌子？' } ] },
    { id: 'family-turning-01', stage: 'family', topic: 'housing', text: '您家是哪年搬到这儿来的？', kind: 'turning', weight: 3, captures: ['move'], sensitivity: 0, followUps: [ { when: [], ask: '为啥搬的？' } ] },
    { id: 'family-turning-02', stage: 'family', topic: 'housing', text: '搬家那天，是咋搬的？', kind: 'detail', weight: 2, captures: ['move'], sensitivity: 0, followUps: [ { when: [], ask: '谁搭的手？' } ] },
    { id: 'family-festival-01', stage: 'family', topic: 'festival', text: '过年，回娘家还是婆家？', kind: 'detail', weight: 3, captures: ['festival', 'marriage'], sensitivity: 1, followUps: [ { when: [], ask: '路上要走多久？' } ] },
    { id: 'family-value-01', stage: 'family', topic: 'marriage', text: '两口子过日子，啥最要紧？', kind: 'value', weight: 3, captures: ['marriage'], sensitivity: 0, followUps: [ { when: ['让', '忍'], ask: '您忍过最大的一回气是啥？' } ] },
    { id: 'family-raising-06', stage: 'family', topic: 'raising', text: '孩子上学，早饭您给做啥？', kind: 'detail', weight: 3, captures: ['children', 'food'], sensitivity: 0, followUps: [ { when: [], ask: '孩子爱吃哪个？' } ] },
    { id: 'family-festival-02', stage: 'family', topic: 'festival', text: '过年给孩子买新衣裳不？', kind: 'detail', weight: 3, captures: ['festival', 'clothes'], sensitivity: 0, followUps: [ { when: ['买'], ask: '新衣裳是啥颜色的？' } ] },
    { id: 'family-raising-07', stage: 'family', topic: 'raising', text: '孩子半夜发烧，您抱他走过夜路不？', kind: 'sensory', weight: 3, captures: ['children', 'illness'], sensitivity: 2, followUps: [ { when: ['走过'], ask: '那晚的月亮亮不亮？' } ] },
    { id: 'family-value-02', stage: 'family', topic: 'raising', text: '孩子小的时候，您有顾不上的时候吗？', kind: 'value', weight: 3, captures: ['children', 'hardship'], sensitivity: 1, followUps: [ { when: ['有'], ask: '那时候心里啥滋味？' } ] },
    // ---------- 中年（22） ----------
    { id: 'midlife-work-01', stage: 'midlife', topic: 'work', text: '您四十来岁那阵子，在哪儿干活？', kind: 'detail', weight: 4, captures: ['job'], sensitivity: 0, followUps: [ { when: [], ask: '那活儿是啥样的？' } ] },
    { id: 'midlife-work-02', stage: 'midlife', topic: 'work', text: '那阵子，您一天睡几个钟头？', kind: 'sensory', weight: 3, captures: ['job'], sensitivity: 0, followUps: [ { when: [], ask: '困得狠了咋办？' } ] },
    { id: 'midlife-work-03', stage: 'midlife', topic: 'work', text: '干活搭伴儿的人，是谁？', kind: 'relation', weight: 3, captures: ['importantPerson'], sensitivity: 0, followUps: [ { when: [], ask: '您俩共事多少年？' } ] },
    { id: 'midlife-illness-01', stage: 'midlife', topic: 'illness', text: '您生过啥大病没有？', kind: 'turning', weight: 4, captures: ['illness'], sensitivity: 2, followUps: [ { when: ['生过'], ask: '那回病，是咋扛过来的？' } ] },
    { id: 'midlife-illness-02', stage: 'midlife', topic: 'illness', text: '病最重那回，谁在跟前？', kind: 'relation', weight: 3, captures: ['illness', 'importantPerson'], sensitivity: 2, followUps: [ { when: [], ask: '守了您几天？' } ] },
    { id: 'midlife-money-01', stage: 'midlife', topic: 'money', text: '那会儿攒钱，是为啥大事？', kind: 'detail', weight: 3, captures: ['money'], sensitivity: 0, followUps: [ { when: [], ask: '那事办成了没有？' } ] },
    { id: 'midlife-money-02', stage: 'midlife', topic: 'money', text: '发工资那天，您先办啥事？', kind: 'detail', weight: 3, captures: ['money'], sensitivity: 0, followUps: [ { when: ['还'], ask: '那账欠了多久？' } ] },
    { id: 'midlife-raising-01', stage: 'midlife', topic: 'raising', text: '孩子念书那几年，您最操心啥？', kind: 'relation', weight: 3, captures: ['children'], sensitivity: 1, followUps: [ { when: [], ask: '操心的事，跟孩子说过不？' } ] },
    { id: 'midlife-raising-02', stage: 'midlife', topic: 'raising', text: '孩子长大了，跟您还亲不？', kind: 'relation', weight: 3, captures: ['children'], sensitivity: 1, followUps: [ { when: [], ask: '孩子们多久来看您一回？' } ] },
    { id: 'midlife-turning-01', stage: 'midlife', topic: 'hardship', text: '那几年，家里最难的一关是啥？', kind: 'turning', weight: 4, captures: ['hardship'], sensitivity: 2, followUps: [ { when: [], ask: '那一关，家里人是咋一起过的？' } ] },
    { id: 'midlife-turning-02', stage: 'midlife', topic: 'joy', text: '哪一年，日子有了盼头？', kind: 'turning', weight: 3, captures: ['importantYear'], sensitivity: 0, followUps: [ { when: [], ask: '那一年有啥不一样？' } ] },
    { id: 'midlife-senses-01', stage: 'midlife', topic: 'senses', text: '车间里，吵不吵？', kind: 'sensory', weight: 3, captures: ['factory'], sensitivity: 0, followUps: [ { when: ['吵'], ask: '机器是啥声儿？' } ] },
    { id: 'midlife-work-04', stage: 'midlife', topic: 'work', text: '厂里发过啥东西没有？', kind: 'detail', weight: 2, captures: ['factory'], sensitivity: 0, followUps: [ { when: ['发过'], ask: '发的啥？' } ] },
    { id: 'midlife-object-01', stage: 'midlife', topic: 'objects', text: '您家那台收音机，是啥牌子？', kind: 'object', weight: 3, captures: ['heirloom'], sensitivity: 0, followUps: [ { when: [], ask: '搁在屋里哪个位置？' } ] },
    { id: 'midlife-senses-02', stage: 'midlife', topic: 'senses', text: '那会儿听收音机，最爱听啥？', kind: 'detail', weight: 3, captures: ['heirloom'], sensitivity: 0, followUps: [ { when: ['评书'], ask: '听的是哪部书？' } ] },
    { id: 'midlife-illness-03', stage: 'midlife', topic: 'illness', text: '您看过赤脚医生没有？', kind: 'detail', weight: 3, captures: ['illness'], sensitivity: 0, followUps: [ { when: ['看过'], ask: '他给您扎针不？' } ] },
    { id: 'midlife-festival-01', stage: 'midlife', topic: 'festival', text: '那会儿过年，最忙的是谁？', kind: 'detail', weight: 2, captures: ['festival'], sensitivity: 0, followUps: [ { when: [], ask: '都忙些啥？' } ] },
    { id: 'midlife-festival-02', stage: 'midlife', topic: 'festival', text: '过年那几天，家里备啥年货？', kind: 'detail', weight: 2, captures: ['festival', 'food'], sensitivity: 0, followUps: [ { when: ['蒸'], ask: '一锅蒸多少？' } ] },
    { id: 'midlife-sensory-01', stage: 'midlife', topic: 'housing', text: '那会儿大冬天，屋里冻过没有？', kind: 'sensory', weight: 3, captures: ['home', 'hardship'], sensitivity: 0, followUps: [ { when: ['冻'], ask: '晚上睡觉，被窝是啥样？' } ] },
    { id: 'midlife-value-01', stage: 'midlife', topic: 'value', text: '四十来岁那会儿，您信哪句话？', kind: 'value', weight: 3, captures: ['catchphrase'], sensitivity: 0, followUps: [ { when: [], ask: '这话谁跟您说的？' } ] },
    { id: 'midlife-sensory-02', stage: 'midlife', topic: 'work', text: '干完活回家，您先干啥？', kind: 'sensory', weight: 3, captures: ['job'], sensitivity: 0, followUps: [ { when: [], ask: '那时候饭好了没？' } ] },
    { id: 'midlife-value-02', stage: 'midlife', topic: 'hardship', text: '日子紧那几年，您愁过啥？', kind: 'value', weight: 3, captures: ['hardship'], sensitivity: 1, followUps: [ { when: [], ask: '愁的事，后来咋样了？' } ] },
    // ---------- 晚年（23） ----------
    { id: 'later-retire-01', stage: 'later', topic: 'work', text: '您是哪年退休的？', kind: 'turning', weight: 4, captures: ['retire'], sensitivity: 0, followUps: [ { when: [], ask: '退休前干到啥岗位？' } ] },
    { id: 'later-retire-02', stage: 'later', topic: 'work', text: '退休头一天，您干啥了？', kind: 'detail', weight: 3, captures: ['retire'], sensitivity: 0, followUps: [ { when: [], ask: '那天心里空落落的不？' } ] },
    { id: 'later-retire-03', stage: 'later', topic: 'work', text: '退休以后，日子空不空？', kind: 'value', weight: 3, captures: ['retire'], sensitivity: 1, followUps: [ { when: ['空'], ask: '空的时候您干啥？' } ] },
    { id: 'later-housing-01', stage: 'later', topic: 'housing', text: '现在住的地方，住得惯不？', kind: 'detail', weight: 3, captures: ['home', 'move'], sensitivity: 0, followUps: [ { when: ['不惯'], ask: '哪儿不惯？' } ] },
    { id: 'later-kin-01', stage: 'later', topic: 'kin', text: '现在家里，谁常来看您？', kind: 'relation', weight: 3, captures: ['importantPerson'], sensitivity: 0, followUps: [ { when: [], ask: '来了都陪您干啥？' } ] },
    { id: 'later-kin-02', stage: 'later', topic: 'kin', text: '孙辈里，哪个跟您最亲？', kind: 'relation', weight: 3, captures: ['children'], sensitivity: 0, followUps: [ { when: [], ask: '那孩子管您叫啥？' } ] },
    { id: 'later-food-01', stage: 'later', topic: 'food', text: '您现在最爱吃啥？跟以前一样不？', kind: 'detail', weight: 3, captures: ['food'], sensitivity: 0, followUps: [ { when: [], ask: '这口儿是打啥时候爱上的？' } ] },
    { id: 'later-sensory-01', stage: 'later', topic: 'illness', text: '天冷了，您哪儿先觉着凉？', kind: 'sensory', weight: 3, captures: ['illness'], sensitivity: 0, followUps: [ { when: [], ask: '凉了您咋暖和过来？' } ] },
    { id: 'later-sensory-02', stage: 'later', topic: 'illness', text: '您夜里，睡得好不？', kind: 'sensory', weight: 3, captures: ['illness'], sensitivity: 1, followUps: [ { when: ['不好'], ask: '睡不着的夜里，您想啥？' } ] },
    { id: 'later-object-01', stage: 'later', topic: 'objects', text: '您手头，还留着啥老物件？', kind: 'object', weight: 4, captures: ['heirloom'], sensitivity: 0, followUps: [ { when: [], ask: '这东西是咋得来的？' } ] },
    { id: 'later-object-02', stage: 'later', topic: 'objects', text: '那本老相册，您常翻不？', kind: 'object', weight: 3, captures: ['heirloom'], sensitivity: 1, followUps: [ { when: ['常'], ask: '最爱看哪一张？' } ] },
    { id: 'later-value-01', stage: 'later', topic: 'joy', text: '这辈子，您最不后悔的一件事是啥？', kind: 'value', weight: 3, captures: ['joy'], sensitivity: 0, followUps: [ { when: [], ask: '那事儿现在想起来还乐不？' } ] },
    { id: 'later-value-02', stage: 'later', topic: 'value', text: '要是能重来，您会改哪一步？', kind: 'value', weight: 3, captures: ['motto'], sensitivity: 1, followUps: [ { when: [], ask: '改了以后，会是啥样？' } ] },
    { id: 'later-value-03', stage: 'later', topic: 'legacy', text: '您觉着，人活一辈子啥最值？', kind: 'value', weight: 3, captures: ['motto'], sensitivity: 0, followUps: [ { when: [], ask: '这话您跟小辈儿说过不？' } ] },
    { id: 'later-kin-03', stage: 'later', topic: 'kin', text: '年轻时候的朋友，还走动不？', kind: 'relation', weight: 3, captures: ['importantPerson'], sensitivity: 0, followUps: [ { when: ['走动'], ask: '见了面唠啥？' } ] },
    { id: 'later-festival-01', stage: 'later', topic: 'festival', text: '今年过年，您家咋过的？', kind: 'detail', weight: 2, captures: ['festival'], sensitivity: 0, followUps: [ { when: [], ask: '年夜饭桌上，谁话最多？' } ] },
    { id: 'later-housing-02', stage: 'later', topic: 'housing', text: '早上起来，您先干点啥？', kind: 'detail', weight: 2, captures: ['home'], sensitivity: 0, followUps: [ { when: [], ask: '这习惯是啥时候有的？' } ] },
    { id: 'later-illness-01', stage: 'later', topic: 'illness', text: '您现在吃药，一天几回？', kind: 'detail', weight: 2, captures: ['illness'], sensitivity: 0, followUps: [ { when: [], ask: '药是饭前吃还是饭后？' } ] },
    { id: 'later-joy-01', stage: 'later', topic: 'joy', text: '最近有啥事，让您高兴了一回？', kind: 'value', weight: 3, captures: ['joy'], sensitivity: 0, followUps: [ { when: [], ask: '那高兴事儿，跟谁说了？' } ] },
    { id: 'later-sensory-03', stage: 'later', topic: 'illness', text: '您如今走道儿，还利索不？', kind: 'sensory', weight: 3, captures: ['illness'], sensitivity: 0, followUps: [ { when: [], ask: '走累了歇哪儿？' } ] },
    { id: 'later-motto-01', stage: 'later', topic: 'legacy', text: '您有啥话，想跟小辈儿说说？', kind: 'value', weight: 4, captures: ['motto'], sensitivity: 0, followUps: [ { when: [], ask: '头一句想说的是啥？' } ] },
    { id: 'later-kin-04', stage: 'later', topic: 'kin', text: '您家老伴儿，身体还好吧？', kind: 'detail', weight: 4, captures: ['marriage', 'importantPerson'], sensitivity: 3, followUps: [ { when: ['走了', '不好'], ask: '您要是想说，就说几句。' } ] },
    { id: 'later-letter-01', stage: 'later', topic: 'letters', text: '您年轻时候，收到过谁的信？', kind: 'detail', weight: 3, captures: ['letter'], sensitivity: 0, followUps: [ { when: [], ask: '那信还在不？' } ] },
    // ---------- 不分年纪（23） ----------
    { id: 'anytime-object-01', stage: 'anytime', topic: 'objects', text: '您家那辆自行车，还在不？', kind: 'object', weight: 3, captures: ['heirloom'], sensitivity: 0, followUps: [ { when: ['在'], ask: '搁在哪儿？' } ] },
    { id: 'anytime-object-02', stage: 'anytime', topic: 'objects', text: '您用过粮票、布票没有？', kind: 'object', weight: 3, captures: ['heirloom', 'money'], sensitivity: 0, followUps: [ { when: ['用过'], ask: '最金贵的是哪张票？' } ] },
    { id: 'anytime-object-03', stage: 'anytime', topic: 'objects', text: '您有啥舍不得扔的东西？', kind: 'object', weight: 3, captures: ['heirloom'], sensitivity: 1, followUps: [ { when: [], ask: '为啥舍不得？' } ] },
    { id: 'anytime-object-04', stage: 'anytime', topic: 'objects', text: '您这辈子，戴过表没有？', kind: 'object', weight: 2, captures: ['heirloom'], sensitivity: 0, followUps: [ { when: ['戴过'], ask: '那表是啥样儿的？' } ] },
    { id: 'anytime-senses-01', stage: 'anytime', topic: 'senses', text: '老家的味儿，您还记得不？', kind: 'sensory', weight: 4, captures: ['birthPlace'], sensitivity: 0, followUps: [ { when: [], ask: '那味儿是啥样儿的？' } ] },
    { id: 'anytime-senses-02', stage: 'anytime', topic: 'senses', text: '您最爱听的声音，是啥？', kind: 'sensory', weight: 3, captures: ['joy'], sensitivity: 0, followUps: [ { when: [], ask: '这声音打哪儿来？' } ] },
    { id: 'anytime-senses-03', stage: 'anytime', topic: 'senses', text: '夏天最热那几天，您咋过？', kind: 'sensory', weight: 3, captures: ['home'], sensitivity: 0, followUps: [ { when: [], ask: '风扇是啥时候买的？' } ] },
    { id: 'anytime-senses-04', stage: 'anytime', topic: 'food', text: '这辈子，您吃过最香的一顿饭是啥？', kind: 'sensory', weight: 4, captures: ['food', 'importantYear'], sensitivity: 0, followUps: [ { when: [], ask: '那顿饭在哪儿吃的？' } ] },
    { id: 'anytime-senses-05', stage: 'anytime', topic: 'senses', text: '您是怕冷，还是怕热？', kind: 'sensory', weight: 2, captures: ['illness'], sensitivity: 0, followUps: [ { when: [], ask: '怕的那头，您咋将就？' } ] },
    { id: 'anytime-kin-01', stage: 'anytime', topic: 'kin', text: '您心里，最要紧的人是哪个？', kind: 'relation', weight: 4, captures: ['importantPerson'], sensitivity: 1, followUps: [ { when: [], ask: '那人好在哪儿？' } ] },
    { id: 'anytime-kin-02', stage: 'anytime', topic: 'kin', text: '您有想念的人不？', kind: 'relation', weight: 4, captures: ['importantPerson'], sensitivity: 2, followUps: [ { when: ['有'], ask: '您要是愿意，就说说那人的样儿。' } ] },
    { id: 'anytime-play-01', stage: 'anytime', topic: 'play', text: '小时候的玩伴，还记得叫啥不？', kind: 'relation', weight: 3, captures: ['importantPerson'], sensitivity: 0, followUps: [ { when: ['记得'], ask: '您俩后来见过面不？' } ] },
    { id: 'anytime-value-01', stage: 'anytime', topic: 'value', text: '您听过最受用的一句话是啥？', kind: 'value', weight: 3, captures: ['catchphrase'], sensitivity: 0, followUps: [ { when: [], ask: '这话是啥时候听见的？' } ] },
    { id: 'anytime-value-02', stage: 'anytime', topic: 'legacy', text: '您觉着，做人最要紧的是啥？', kind: 'value', weight: 3, captures: ['motto'], sensitivity: 0, followUps: [ { when: [], ask: '这理儿是谁教的？' } ] },
    { id: 'anytime-value-03', stage: 'anytime', topic: 'value', text: '您这辈子，说过最后悔的话没有？', kind: 'value', weight: 3, captures: ['motto'], sensitivity: 2, followUps: [ { when: ['说过'], ask: '那句话，后来圆回来没有？' } ] },
    { id: 'anytime-value-04', stage: 'anytime', topic: 'value', text: '您佩服过啥样的人？', kind: 'value', weight: 3, captures: ['importantPerson'], sensitivity: 0, followUps: [ { when: [], ask: '那人做了啥事让您佩服？' } ] },
    { id: 'anytime-turning-01', stage: 'anytime', topic: 'hardship', text: '这辈子，最难的一个决定是啥？', kind: 'turning', weight: 3, captures: ['importantYear'], sensitivity: 1, followUps: [ { when: [], ask: '那决定，是咋下的？' } ] },
    { id: 'anytime-turning-02', stage: 'anytime', topic: 'value', text: '要是挑一年代表您这辈子，您挑哪年？', kind: 'turning', weight: 4, captures: ['importantYear'], sensitivity: 1, followUps: [ { when: [], ask: '那年出了啥事？' } ] },
    { id: 'anytime-name-01', stage: 'anytime', topic: 'name', text: '您的名字，是谁给起的？', kind: 'detail', weight: 4, captures: ['babyName'], sensitivity: 0, followUps: [ { when: [], ask: '起名儿有啥讲究？' } ] },
    { id: 'anytime-name-02', stage: 'anytime', topic: 'name', text: '您名字里头，藏着啥意思？', kind: 'detail', weight: 3, captures: ['babyName'], sensitivity: 0, followUps: [ { when: [], ask: '这意思是谁跟您说的？' } ] },
    { id: 'anytime-kin-03', stage: 'anytime', topic: 'kin', text: '您家的孩子们，如今都好吧？', kind: 'detail', weight: 4, captures: ['children'], sensitivity: 3, followUps: [ { when: [], ask: '孩子们都忙啥呢？' } ] },
    { id: 'anytime-hardship-01', stage: 'anytime', topic: 'hardship', text: '您家里，有没有走散过的人？', kind: 'detail', weight: 3, captures: ['importantPerson'], sensitivity: 3, followUps: [ { when: ['有'], ask: '后来找着了没有？' } ] },
    { id: 'anytime-hardship-02', stage: 'anytime', topic: 'hardship', text: '那几年运动多，家里受过牵连没有？', kind: 'detail', weight: 3, captures: ['hardship'], sensitivity: 3, followUps: [ { when: ['受过'], ask: '您要是愿意，就说点。' } ] },
  ],

  followUpRules: [
    // ---------- 全局触发式追问规则（48） ----------
    { id: 'rule-hungry', when: ['饿', '没吃上', '吃不饱'], stage: 'any', asks: ['那时候一天能吃上几顿？', '最饿的时候，您想的是啥？'], sensitivity: 2, why: '饥饿是身体记忆，最容易带出年代细节；只顺问体验，不追问原因、不评判。' },
    { id: 'rule-rain', when: ['下雨', '漏雨'], stage: 'any', asks: ['屋里漏雨的时候，您咋睡的？', '下雨天您都干点啥？'], sensitivity: 0, why: '天气是共同话题，顺着能进到屋里、路上的具体日子。' },
    { id: 'rule-cold', when: ['冷', '冻'], stage: 'any', asks: ['那会儿冬天您咋过的？', '手冻了咋办？'], sensitivity: 0, why: '冷是身体记忆，带出穿戴、取暖和冬天的活计。' },
    { id: 'rule-hot', when: ['热', '晒'], stage: 'any', asks: ['热的时候上哪儿凉快去？'], sensitivity: 0, why: '热天记忆连着住处、歇晌和农活。' },
    { id: 'rule-walk', when: ['走', '路'], stage: 'any', asks: ['那一趟得走多久？', '路上累不累？'], sensitivity: 0, why: '老人常以"走路"丈量时间，追问路程能还原空间与辛苦。' },
    { id: 'rule-carry', when: ['背', '挑', '扛'], stage: 'any', asks: ['背的是啥？多重？'], sensitivity: 0, why: '负重是具体动作，一问就能回到当时的肩膀和力气。' },
    { id: 'rule-spring', when: ['春', '开春'], stage: 'any', asks: ['开春头一件事是啥？'], sensitivity: 0, why: '农时是集体记忆的锚点，开春连着播种和一年的盼头。' },
    { id: 'rule-autumn', when: ['秋', '收'], stage: 'any', asks: ['收秋那阵子，全家都咋忙？'], sensitivity: 0, why: '秋收是一家老小齐上阵的场景，最容易讲出画面。' },
    { id: 'rule-newyear', when: ['过年', '春节', '年三十'], stage: 'any', asks: ['那会儿过年，您家都备啥？', '年夜饭最盼的是哪道菜？'], sensitivity: 0, why: '过年是全年细节最密的记忆，蒸炸炖煮全在里头。' },
    { id: 'rule-festival', when: ['赶集', '庙会', '集市'], stage: 'any', asks: ['赶集都买啥？', '集上最热闹的是啥？'], sensitivity: 0, why: '集市是乡土社会的窗口，连买卖带人情都能带出来。' },
    { id: 'rule-sugar', when: ['糖', '甜'], stage: 'any', asks: ['那会儿糖是啥糖？', '甜东西多久吃一回？'], sensitivity: 0, why: '甜是稀缺记忆，能带出零食、过年和家里的讲究。' },
    { id: 'rule-meat', when: ['肉', '荤'], stage: 'any', asks: ['那会儿吃肉，多久一回？', '肉是咋做的？'], sensitivity: 0, why: '吃肉频率是生活水平的直接刻度，又具体又好答。' },
    { id: 'rule-rice', when: ['米', '面', '馒头', '窝头'], stage: 'any', asks: ['细粮是啥时候吃？'], sensitivity: 0, why: '粗细粮之分是年代细节，顺口就能问出礼数和紧巴。' },
    { id: 'rule-sick', when: ['病', '烧', '疼'], stage: 'any', asks: ['那回病，谁照看您？', '好了以后忌口不？'], sensitivity: 1, why: '生病回忆牵动照看的人，只问照料与恢复，不碰病情是非。' },
    { id: 'rule-cry', when: ['哭', '掉泪'], stage: 'any', asks: ['那回是咋回事？'], sensitivity: 2, why: '老人主动提到哭，说明愿意说；顺着听，不劝、不打断。' },
    { id: 'rule-laugh', when: ['笑', '乐'], stage: 'any', asks: ['啥事这么乐？'], sensitivity: 0, why: '笑声是最轻快的入口，顺着乐事问，气氛最好。' },
    { id: 'rule-ma', when: ['娘', '妈'], stage: 'any', asks: ['您娘是啥样的人？', '娘最拿手的是啥饭？'], sensitivity: 0, why: '提到娘往往连着吃食和手艺，娘是多数老人最愿讲的人。' },
    { id: 'rule-pa', when: ['爹', '爸', '父亲'], stage: 'any', asks: ['您爹年轻时候啥脾气？'], sensitivity: 0, why: '爹的记忆常与干活、规矩相连，一问脾气就能铺开。' },
    { id: 'rule-brother', when: ['哥', '兄长'], stage: 'any', asks: ['您俩小时候谁管谁？'], sensitivity: 0, why: '手足排行是童年的框架，顺着问出谁带谁、谁护谁。' },
    { id: 'rule-sister', when: ['姐', '妹'], stage: 'any', asks: ['您俩小时候老在一块儿不？'], sensitivity: 0, why: '姐妹情常藏在针线、灶台这些小事里，别问嫁娶。' },
    { id: 'rule-sibling', when: ['兄弟', '姊妹', '姐弟', '兄妹'], stage: 'any', asks: ['您家孩子里头，您排老几？'], sensitivity: 0, why: '排行决定小时候的活计和待遇，是传记里的一根轴。' },
    { id: 'rule-school', when: ['上学', '念书', '学堂'], stage: 'any', asks: ['学堂离您家多远？', '老师里头，哪个您记得最清？'], sensitivity: 0, why: '上学连着路、课、老师，是讲故事最顺的线头。' },
    { id: 'rule-teacher', when: ['老师', '先生'], stage: 'any', asks: ['那位老师是啥样人？', '他教您啥？'], sensitivity: 0, why: '老师是老人记忆里的长辈形象，顺着能讲出规矩和体面。' },
    { id: 'rule-lesson', when: ['课文', '写字', '毛笔'], stage: 'any', asks: ['头一篇课文是啥？'], sensitivity: 0, why: '课文是能背出来的记忆，一开口就是当年的声音。' },
    { id: 'rule-work', when: ['干活', '出工', '上工'], stage: 'any', asks: ['那活儿咋干？', '干一天累不累？'], sensitivity: 0, why: '干活是主叙事，追问动作和累不累，画面自然出来。' },
    { id: 'rule-wage', when: ['工钱', '工资', '挣'], stage: 'youth', asks: ['挣的钱都花在哪儿？', '头一回挣钱是啥时候？'], sensitivity: 0, why: '头一回挣钱是人生转折点，青年阶段最值得细问。' },
    { id: 'rule-ration', when: ['粮票', '布票', '票证'], stage: 'any', asks: ['那会儿啥都得凭票不？', '票是咋发的？'], sensitivity: 0, why: '票证是年代的实物锚点，老人一说就回到那个年代。' },
    { id: 'rule-money', when: ['钱', '攒', '借'], stage: 'any', asks: ['借钱跟谁借的？', '还了多久才还上？'], sensitivity: 1, why: '借钱见人情也见难处，只问过程和还账，不评判。' },
    { id: 'rule-bike', when: ['自行车', '骑车'], stage: 'any', asks: ['那辆车是啥牌子？', '谁学会骑的？'], sensitivity: 0, why: '自行车是大件记忆，牌子、学车都是具体画面。' },
    { id: 'rule-radio', when: ['收音机', '广播'], stage: 'any', asks: ['最爱听啥节目？', '广播几点响？'], sensitivity: 0, why: '收音机把年代的声音请回屋里，评书、新闻都是话题。' },
    { id: 'rule-film', when: ['电影', '看电影'], stage: 'any', asks: ['在哪儿看的？', '看的是啥片子？'], sensitivity: 0, why: '露天电影是集体记忆，连着走夜路和热闹。' },
    { id: 'rule-opera', when: ['戏', '唱戏', '听戏'], stage: 'any', asks: ['唱的是哪一出？', '您会哼两句不？'], sensitivity: 0, why: '戏文是老人背得动的记忆，哼两句最出气氛。' },
    { id: 'rule-train', when: ['火车', '坐车', '进城'], stage: 'any', asks: ['头一回坐是去哪儿？', '车票多少钱？'], sensitivity: 0, why: '头一回出远门是叙事高峰，火车票价是年代刻度。' },
    { id: 'rule-letter', when: ['信', '写信', '邮'], stage: 'any', asks: ['信是写给谁的？', '寄一封信要多久？'], sensitivity: 0, why: '信连着等待和牵挂，一问收信人就能牵出人来。' },
    { id: 'rule-marry', when: ['结婚', '成家', '娶', '嫁'], stage: 'family', asks: ['那会儿结婚，家里办了几桌？', '您穿的是啥？'], sensitivity: 0, why: '成家阶段的婚事细节最密，桌数、衣裳都是画面。' },
    { id: 'rule-baby', when: ['娃', '孩子', '坐月子'], stage: 'family', asks: ['头一胎在哪儿生的？', '坐月子吃啥补？'], sensitivity: 1, why: '生养是家史核心，只问过程和吃喝，不追问难产之类。' },
    { id: 'rule-raise', when: ['养', '拉扯', '带大'], stage: 'family', asks: ['拉扯孩子，最费劲的是啥？'], sensitivity: 1, why: '拉扯二字自带辛苦，顺着问最费劲的，不碰偏心之类。' },
    { id: 'rule-military', when: ['当兵', '部队', '参军'], stage: 'youth', asks: ['在哪儿当的兵？', '当兵几年？'], sensitivity: 0, why: '当兵是青年阶段的大转折，地点和年数先搭框架。' },
    { id: 'rule-factory', when: ['厂', '上班', '车间'], stage: 'midlife', asks: ['厂里生产啥？', '三班倒不？'], sensitivity: 0, why: '中年阶段的工厂叙事，产品、班次都是具体抓手。' },
    { id: 'rule-country', when: ['下乡', '知青', '插队'], stage: 'youth', asks: ['下到哪个村？', '干了几年？'], sensitivity: 1, why: '下乡是沉重记忆，先问地点年数搭框架，不逼问遭遇。' },
    { id: 'rule-retire', when: ['退休', '退下来'], stage: 'later', asks: ['退休以后，您都干点啥？'], sensitivity: 0, why: '退休是晚年叙事的开头，顺着问日后的活法。' },
    { id: 'rule-dream', when: ['梦', '做梦'], stage: 'any', asks: ['梦见啥了？', '那梦现在还记得不？'], sensitivity: 1, why: '老人主动提梦说明愿讲，梦连着放不下的人和事，只听不析。' },
    { id: 'rule-fear', when: ['怕', '吓'], stage: 'any', asks: ['您怕的是啥？', '那时候咋缓过来的？'], sensitivity: 1, why: '怕的记忆连着具体的物和夜，问怎么缓过来是顺着照顾情绪。' },
    { id: 'rule-happy', when: ['高兴', '乐呵', '美'], stage: 'any', asks: ['那回是因为啥？', '现在想起来还乐不？'], sensitivity: 0, why: '高兴事要趁热追问原因，乐呵能撑起整段谈话。' },
    { id: 'rule-craft', when: ['手艺', '学'], stage: 'any', asks: ['跟谁学的？', '头一件活儿做成啥样？'], sensitivity: 0, why: '手艺连着师傅和头一件作品，最出细节。' },
    { id: 'rule-neighbor', when: ['邻居', '街坊', '隔壁'], stage: 'any', asks: ['街坊里，谁家跟您家最好？'], sensitivity: 0, why: '邻里是人情网络的入口，顺着问出走动和帮忙。' },
    { id: 'rule-sickbed', when: ['住院', '医院', '打针'], stage: 'any', asks: ['谁陪您去的？', '医院是啥样？'], sensitivity: 1, why: '住院记忆连着陪护的人，先问陪伴再问环境，不深挖病情。' },
    { id: 'rule-home', when: ['家', '院子', '房子'], stage: 'any', asks: ['那院子是啥样？', '院里种了啥？'], sensitivity: 0, why: '院子是记忆的舞台，树、井、鸡窝都是具体画面。' },
  ],

  refusalReplies: [
    '那咱不说这个。',
    '行，咱换个话题。',
    '嗯，这事儿咱不念叨了。',
    '好嘞，那咱说点别的。',
    '不说了不说了，您喝口水。',
    '成，咱聊点您乐意说的。',
    '那咱就不提它了。',
    '好，那咱说点轻快的。',
    '行，听您的。',
    '不问了，咱说别的。',
    '好，那这事咱撂下。',
    '嗯，咱聊点高兴的。',
    '成，您说了算。',
    '那咱就不往下问了。',
    '行，咱说点旁的。',
  ],

  silenceReplies: [
    '您慢慢想，我不催。',
    '不着急，啥时候想起来啥时候说。',
    '咱歇口气儿，不赶趟。',
    '我就在这儿陪着您。',
    '要不，咱从一件小事儿说起。',
    '您小时候，先想起的是啥？',
    '那会儿天天吃的，您还记得不？',
    '您起先住的屋，是啥样子？',
    '您要是不想说，咱就坐会儿。',
    '咱慢慢来，不急这一时半会儿。',
    '您想起来一点是一点。',
    '那会儿家里都有啥人？',
    '您记事儿最早，是多大？',
    '头一件让您记住的事儿，是啥？',
    '咱不非得说那些，说点旁的也行。',
  ],

  // 呼吸拍：老人说了句有分量的话，这一拍不追问、只接住。AI 开着时由 AI 润色成更熨帖的回应，
  // 这里只留"没开 AI 也能接住"的兜底。全是共情，一句都不带问题。
  beatReplies: [
    '哎，那可真是。',
    '这话听着，我心里头热乎。',
    '那日子，可真够您扛的。',
    '哎哟，那可真不容易。',
    '嗯，您说，我记着。',
    '这话，我搁心里头了。',
    '可不是嘛。',
    '您放心，我听着呢。',
  ],

  repeatReplies: [
    '这事儿，您一准记在心里头。',
    '您再说说，我爱听。',
    '这事儿对您要紧，您多念叨念叨。',
    '嗯，我记下了。',
    '您说着，我听着呢。',
    '这茬儿在您心里头占着地方呢。',
    '您讲，我不嫌烦。',
    '您说的这些，我都好好记着。',
    '您再给我细说说。',
    '这一定是您心里最要紧的。',
    '您慢慢说，我慢慢听。',
    '您说多少回，我都愿意听。',
    '这回事，您记得真清楚。',
    '您愿意说，我就愿意听。',
    '您这些话，我都搁在心里了。',
  ],

  warmups: [
    '我头一个想问的，是您最开始记事儿的时候。',
    '咱不寒暄，我上来就想问您一件事。',
    '我把您这一辈子记下来，就从最早那一段问起。',
    '我心里头第一个想问的，是您起先那段日子。',
    '我这一趟是来记您的一辈子的，头一个咱说您小时候。',
    '咱直接说，从您记事儿那会儿讲起。',
  ],

  closings: [
    '今儿个跟您说话，我心里头暖和。',
    '您说的这些，我都记下了。',
    '您歇着吧，我改天再来。',
    '今儿个听您讲了这么多，真好。',
    '您好好歇着，咱下回接着说。',
    '您说的，我都搁在心里了。',
    '天不早了，您早点歇着。',
    '我走了，您有事儿招呼我。',
    '今儿个麻烦您了，跟您说话我长见识。',
    '您保重身体，咱下回见。',
    '您说的每句话，我都当回事儿。',
    '下回我还来，您还给我讲。',
    '您歇好了，我再来看您。',
    '今儿个真舍不得走，您说的我都记住了。',
  ],

  notUnderstoodReplies: [
    '我这耳朵笨，您再说一遍呗。',
    '我这脑瓜子转得慢，您慢点说。',
    '哎哟，我这耳朵没听清，您再念叨念叨。',
    '您说得快，我没跟上，您再说说。',
    '我这耳朵不济事，劳您再说一回。',
    '您刚才那句，我没听真，您再说说。',
    '我这人笨，您那句话我没弄明白，您再给我说说。',
    '您慢慢说，我好好听。',
    '我年纪轻，听得囫囵，您再说细点呗。',
    '您这话我不大明白，您再给我讲讲。',
    '我这耳朵背，您大声点，别累着您嗓子。',
    '您再给我说一遍，我记住了。',
    '您这话我没听全，让家里人帮您说给我听也行。',
  ],

  profileFields: [
    { id: 'food', name: '吃食', kind: 'text' },
    { id: 'birthPlace', name: '出生地方', kind: 'text' },
    { id: 'babyName', name: '乳名', kind: 'text' },
    { id: 'parents', name: '父母', kind: 'text' },
    { id: 'siblings', name: '兄弟姐妹', kind: 'text' },
    { id: 'home', name: '住处', kind: 'text' },
    { id: 'school', name: '学堂', kind: 'text' },
    { id: 'firstJob', name: '第一份活计', kind: 'text' },
    { id: 'job', name: '干的活', kind: 'text' },
    { id: 'craft', name: '手艺', kind: 'text' },
    { id: 'marriage', name: '婚嫁', kind: 'text' },
    { id: 'children', name: '儿女', kind: 'text' },
    { id: 'move', name: '搬迁', kind: 'text' },
    { id: 'military', name: '当兵', kind: 'text' },
    { id: 'factory', name: '进厂', kind: 'text' },
    { id: 'countryside', name: '下乡', kind: 'text' },
    { id: 'illness', name: '生病', kind: 'text' },
    { id: 'retire', name: '退休', kind: 'text' },
    { id: 'heirloom', name: '老物件', kind: 'text' },
    { id: 'catchphrase', name: '口头禅', kind: 'text' },
    { id: 'importantPerson', name: '最要紧的人', kind: 'text' },
    { id: 'importantYear', name: '最要紧的一年', kind: 'text' },
    { id: 'motto', name: '想留给后人的话', kind: 'text' },
    { id: 'clothes', name: '穿戴', kind: 'text' },
    { id: 'money', name: '钱', kind: 'text' },
    { id: 'travel', name: '远行', kind: 'text' },
    { id: 'festival', name: '节令', kind: 'text' },
    { id: 'letter', name: '信', kind: 'text' },
    { id: 'hardship', name: '最难的时候', kind: 'text' },
    { id: 'joy', name: '最高兴的时候', kind: 'text' }
  ]
};
