// 人生之书：方言支持包
// 纯数据，机器可检查。用途：
//   1. askForms —— 把标准问句换成老人听得惯的方言说法，AI 念给老人听。
//   2. lexicon/kinship —— 老人的话转成文字后的方言词 → 普通话对照，方便后代看懂传记。
//   3. confusions —— 语音听写易错音对照，供"家人协助纠错"生成候选。
// 本文件不做语音识别，只做词表与说法映射。每一条都必须是真实存在的用法。
// 铁律：不确定的词宁可删掉，绝不编造。

export const dialects = {
  version: '1.0',

  packs: [
    {
      id: 'dongbei',
      name: '东北话',
      area: '黑龙江、吉林、辽宁',
      speechLang: 'zh-CN',
      speechNote: '普通话听写基本能认，个别土话会听错。',

      lexicon: [
        { dialect: '苞米', standard: '玉米', note: '' },
        { dialect: '嘎哈', standard: '干什么', note: '' },
        { dialect: '咋整', standard: '怎么办', note: '' },
        { dialect: '埋汰', standard: '脏、不干净', note: '' },
        { dialect: '唠嗑', standard: '聊天', note: '' },
        { dialect: '得瑟', standard: '张扬、炫耀', note: '' },
        { dialect: '磕碜', standard: '难看、丢人', note: '' },
        { dialect: '稀罕', standard: '喜欢', note: '' },
        { dialect: '贼', standard: '很、非常', note: '' },
        { dialect: '整', standard: '做、弄', note: '' },
        { dialect: '磨叽', standard: '啰嗦、办事拖拉', note: '' },
        { dialect: '膈应', standard: '讨厌、反感', note: '' },
        { dialect: '秃噜', standard: '滑脱；说走了嘴', note: '' },
        { dialect: '波棱盖', standard: '膝盖', note: '' },
        { dialect: '大碴子', standard: '大颗玉米粒（煮粥用）', note: '' },
        { dialect: '粘豆包', standard: '黄米面豆包', note: '' },
        { dialect: '酸菜', standard: '腌渍的大白菜', note: '' },
        { dialect: '血肠', standard: '猪血灌肠', note: '' },
        { dialect: '火炕', standard: '烧火取暖的炕', note: '' },
        { dialect: '灶坑', standard: '灶膛', note: '' },
        { dialect: '锅台', standard: '灶台', note: '' },
        { dialect: '棉猴', standard: '带帽子的棉大衣', note: '' },
        { dialect: '晌午', standard: '中午', note: '' },
        { dialect: '后晌', standard: '下午', note: '' },
        { dialect: '头晌', standard: '上午', note: '' },
        { dialect: '天头', standard: '天气', note: '' },
        { dialect: '冷丁', standard: '突然', note: '' },
        { dialect: '麻溜', standard: '快、利索', note: '' },
        { dialect: '寻思', standard: '想、琢磨', note: '' },
        { dialect: '合计', standard: '商量、盘算', note: '' },
        { dialect: '打怵', standard: '害怕、发怵', note: '' },
        { dialect: '屯子', standard: '村庄', note: '' },
        { dialect: '庄稼人', standard: '农民', note: '' },
        { dialect: '垧', standard: '土地面积单位，一垧约合十五亩', note: '' },
        { dialect: '打场', standard: '给庄稼脱粒', note: '' },
        { dialect: '扬场', standard: '借风力把粮食和糠分开', note: '' },
        { dialect: '歇晌', standard: '午休', note: '' },
        { dialect: '卖呆', standard: '看热闹、发呆', note: '' },
        { dialect: '掰扯', standard: '分辨、讲理', note: '' },
        { dialect: '咋地', standard: '怎么', note: '' },
        { dialect: '拉倒', standard: '算了', note: '' },
        { dialect: '白瞎', standard: '可惜', note: '' },
        { dialect: '造', standard: '吃（大口吃）', note: '' },
        { dialect: '可劲儿', standard: '使劲儿', note: '' },
        { dialect: '好使', standard: '管用', note: '' },
        { dialect: '忽悠', standard: '哄骗、说大话', note: '' },
        { dialect: '搁', standard: '放、放在', note: '' },
        { dialect: '薅', standard: '拔', note: '' },
        { dialect: '撂', standard: '放下', note: '' },
        { dialect: '干仗', standard: '打架', note: '' },
        { dialect: '掐架', standard: '吵架、打架', note: '' },
        { dialect: '串门儿', standard: '到别人家做客', note: '' },
        { dialect: '赶集', standard: '去集市', note: '' },
        { dialect: '年根儿', standard: '年底', note: '' },
        { dialect: '洋柿子', standard: '西红柿', note: '老说法' },
        { dialect: '大头菜', standard: '卷心菜', note: '' },
        { dialect: '倭瓜', standard: '南瓜', note: '' },
        { dialect: '角瓜', standard: '西葫芦', note: '' },
        { dialect: '饽饽', standard: '馒头、饼类面食', note: '' },
        { dialect: '大饼子', standard: '玉米面做的大饼', note: '' },
        { dialect: '大碴粥', standard: '大碴子煮的粥', note: '' },
        { dialect: '二米饭', standard: '大米小米混合焖的饭', note: '' },
        { dialect: '毛嗑', standard: '葵花籽', note: '' },
        { dialect: '大果子', standard: '油条', note: '' },
        { dialect: '干豆腐', standard: '豆腐皮（千张）', note: '' },
        { dialect: '冻梨', standard: '冻过的梨', note: '' },
        { dialect: '卡秃噜皮', standard: '磕破皮', note: '' }
      ],

      kinship: [
        { dialect: '老儿子', standard: '最小的儿子', note: '' },
        { dialect: '老闺女', standard: '最小的女儿', note: '' },
        { dialect: '大爷', standard: '伯父（父亲的哥哥）', note: '' },
        { dialect: '老叔', standard: '最小的叔叔', note: '' },
        { dialect: '婶儿', standard: '婶婶', note: '' },
        { dialect: '老姨', standard: '最小的姨妈', note: '' },
        { dialect: '姥姥', standard: '外祖母', note: '' },
        { dialect: '姥爷', standard: '外祖父', note: '' },
        { dialect: '爹', standard: '爸爸（旧时称呼）', note: '' },
        { dialect: '姑娘', standard: '女儿', note: '老人常说"我家姑娘"' },
        { dialect: '小子', standard: '儿子、男孩', note: '' },
        { dialect: '老疙瘩', standard: '最小的孩子', note: '' },
        { dialect: '媳妇儿', standard: '妻子', note: '' },
        { dialect: '大伯子', standard: '丈夫的哥哥', note: '' },
        { dialect: '小叔子', standard: '丈夫的弟弟', note: '' },
        { dialect: '大姑子', standard: '丈夫的姐姐', note: '' },
        { dialect: '小姑子', standard: '丈夫的妹妹', note: '' },
        { dialect: '大姨子', standard: '妻子的姐姐', note: '' },
        { dialect: '小姨子', standard: '妻子的妹妹', note: '' },
        { dialect: '外甥', standard: '姐妹的儿子', note: '' },
        { dialect: '侄子', standard: '兄弟的儿子', note: '' },
        { dialect: '连襟', standard: '妻子的姐妹的丈夫', note: '' },
        { dialect: '妯娌', standard: '兄弟的妻子们之间互称', note: '' },
        { dialect: '亲家', standard: '子女配偶的父母', note: '' }
      ],

      askForms: [
        { standardAsk: '您小时候最愿意吃啥饭？', localAsk: '您小时候最稀罕吃啥饭？' },
        { standardAsk: '您家住在哪儿？', localAsk: '您家在哪儿住？' },
        { standardAsk: '您平时干什么？', localAsk: '您平时都嘎哈？' },
        { standardAsk: '您身体怎么样？', localAsk: '您身子骨咋样？' },
        { standardAsk: '您昨天去哪儿了？', localAsk: '您昨儿上哪儿去了？' },
        { standardAsk: '您晚上几点睡？', localAsk: '您晚上几点睡？' },
        { standardAsk: '您小时候上过学吗？', localAsk: '您小时候念过书没？' },
        { standardAsk: '您有几个孩子？', localAsk: '您家几个孩子？' },
        { standardAsk: '您是什么时候结婚的？', localAsk: '您啥时候结的婚？' },
        { standardAsk: '您觉得那时候日子苦吗？', localAsk: '您觉着那阵子日子苦不苦？' },
        { standardAsk: '您平时和谁聊天？', localAsk: '您平时跟谁唠嗑？' },
        { standardAsk: '您愿意给我讲讲您的事吗？', localAsk: '您愿意跟我唠唠您的事儿不？' },
        { standardAsk: '您还记得小时候的事吗？', localAsk: '您还记着小时候的事儿不？' },
        { standardAsk: '您喜欢吃什么菜？', localAsk: '您愿意吃啥菜？' },
        { standardAsk: '您冷不冷？', localAsk: '您觉着冷不冷？' },
        { standardAsk: '您还有什么想说的吗？', localAsk: '您还有啥想说的？' }
      ],

      confusions: [
        { heard: '人', shouldBe: '银', note: '东北部分地区 r 声母读成 y' },
        { heard: '肉', shouldBe: '又', note: 'r 声母读成 y' },
        { heard: '热', shouldBe: '夜', note: 'r 声母读成 y' },
        { heard: '让', shouldBe: '样', note: 'r 声母读成 y' },
        { heard: '软', shouldBe: '远', note: 'r 声母读成 y' },
        { heard: '日头', shouldBe: '意头', note: '"日头"（太阳）的 r 读成 y' },
        { heard: '认', shouldBe: '印', note: 'r 声母读成 y' },
        { heard: '绕', shouldBe: '药', note: 'r 声母读成 y' },
        { heard: '染', shouldBe: '眼', note: 'r 声母读成 y' },
        { heard: '润', shouldBe: '运', note: 'r 声母读成 y' },
        { heard: '三', shouldBe: '山', note: '平舌化，sh 读成 s' },
        { heard: '四', shouldBe: '是', note: '平舌化，sh 读成 s' },
        { heard: '呲', shouldBe: '吃', note: '平舌化，ch 读成 c' }
      ],

      flavor: ['整', '贼', '咋', '啥', '唠', '稀罕', '可劲儿', '麻溜', '白瞎', '拉倒']
    },

    {
      id: 'xian',
      name: '西安话（关中）',
      area: '陕西关中地区',
      speechLang: 'zh-CN',
      speechNote: '普通话听写能认出大意，"咥、谝、嫽"这类土话容易听错。',

      lexicon: [
        { dialect: '咥', standard: '吃（大口吃）', note: '咥饭就是吃饭' },
        { dialect: '谝', standard: '聊天、闲谈', note: '' },
        { dialect: '谝闲传', standard: '聊天、拉家常', note: '' },
        { dialect: '麻达', standard: '麻烦、问题', note: '有麻达=有问题' },
        { dialect: '嫽', standard: '好、美', note: '' },
        { dialect: '嫽咋咧', standard: '好极了', note: '' },
        { dialect: '美得很', standard: '非常好', note: '' },
        { dialect: '碎娃', standard: '小孩子', note: '' },
        { dialect: '娃', standard: '孩子', note: '' },
        { dialect: '碎', standard: '小', note: '碎=小，如碎娃' },
        { dialect: '做啥', standard: '干什么', note: '' },
        { dialect: '啥', standard: '什么', note: '' },
        { dialect: '咋咧', standard: '怎么了', note: '' },
        { dialect: '咧', standard: '了（语气词）', note: '' },
        { dialect: '苞谷', standard: '玉米', note: '' },
        { dialect: '洋芋', standard: '土豆', note: '' },
        { dialect: '红苕', standard: '红薯', note: '' },
        { dialect: '锅盔', standard: '大而厚的烤饼', note: '' },
        { dialect: '馍', standard: '馒头、饼类面食', note: '' },
        { dialect: '蒸馍', standard: '馒头', note: '' },
        { dialect: '扯面', standard: '手工拉制的宽面', note: '' },
        { dialect: '油泼面', standard: '用热油泼辣子的面', note: '' },
        { dialect: '臊子面', standard: '带臊子的汤面', note: '' },
        { dialect: '肉夹馍', standard: '腊汁肉夹馍', note: '' },
        { dialect: '凉皮', standard: '凉拌面皮', note: '' },
        { dialect: '面皮', standard: '凉皮', note: '' },
        { dialect: '电壶', standard: '暖水瓶', note: '' },
        { dialect: '洋火', standard: '火柴', note: '老说法' },
        { dialect: '黑了', standard: '晚上', note: '' },
        { dialect: '屋里', standard: '家里', note: '' },
        { dialect: '婆娘', standard: '妻子', note: '' },
        { dialect: '老汉', standard: '丈夫、老年男子', note: '' },
        { dialect: '媳妇', standard: '妻子、儿媳', note: '' },
        { dialect: '啬皮', standard: '小气、吝啬', note: '' },
        { dialect: '瓜', standard: '傻', note: '' },
        { dialect: '瓜娃', standard: '傻孩子', note: '' },
        { dialect: '哈怂', standard: '坏家伙', note: '' },
        { dialect: '美气', standard: '舒服、惬意', note: '' },
        { dialect: '圪蹴', standard: '蹲', note: '' },
        { dialect: '下地', standard: '去地里干活', note: '' },
        { dialect: '收麦', standard: '收割麦子', note: '' },
        { dialect: '拾掇', standard: '收拾', note: '' },
        { dialect: '扎势', standard: '摆架子、显摆', note: '' },
        { dialect: '怂', standard: '家伙（对人的戏称）', note: '' }
      ],

      kinship: [
        { dialect: '大', standard: '爸爸', note: '关中背称父亲为"大"' },
        { dialect: '娘', standard: '妈妈', note: '旧时称呼' },
        { dialect: '爷', standard: '爷爷', note: '' },
        { dialect: '婆', standard: '奶奶', note: '' },
        { dialect: '外爷', standard: '外公', note: '' },
        { dialect: '外婆', standard: '外婆', note: '' },
        { dialect: '姑', standard: '姑姑', note: '' },
        { dialect: '姨', standard: '姨妈', note: '' },
        { dialect: '舅', standard: '舅舅', note: '' },
        { dialect: '媳妇', standard: '妻子', note: '' },
        { dialect: '老汉', standard: '丈夫', note: '' },
        { dialect: '女婿', standard: '女儿的丈夫', note: '' },
        { dialect: '外甥', standard: '姐妹的儿子', note: '' },
        { dialect: '亲家', standard: '子女配偶的父母', note: '' }
      ],

      askForms: [
        { standardAsk: '您小时候最愿意吃啥饭？', localAsk: '你小时候最爱咥啥饭？' },
        { standardAsk: '您家住在哪儿？', localAsk: '你屋在啥地方？' },
        { standardAsk: '您平时干什么？', localAsk: '你平时都做啥？' },
        { standardAsk: '您身体怎么样？', localAsk: '你身体咋样？' },
        { standardAsk: '您昨天去哪儿了？', localAsk: '你昨天到哪儿去了？' },
        { standardAsk: '您晚上几点睡？', localAsk: '你黑咧几点睡？' },
        { standardAsk: '您小时候上过学吗？', localAsk: '你小时候念过书没？' },
        { standardAsk: '您有几个孩子？', localAsk: '你屋有几口人？' },
        { standardAsk: '您是什么时候结婚的？', localAsk: '你啥时候结的婚？' },
        { standardAsk: '您觉得那时候日子苦吗？', localAsk: '你觉着那阵子日子苦不苦？' },
        { standardAsk: '您平时和谁聊天？', localAsk: '你闲了跟谁谝闲传？' },
        { standardAsk: '您愿意给我讲讲您的事吗？', localAsk: '你愿意跟我谝一谝不？' },
        { standardAsk: '您还记得小时候的事吗？', localAsk: '你还记得小时候的事儿不？' },
        { standardAsk: '您觉得累不累？', localAsk: '你觉着乏不乏？' },
        { standardAsk: '您冷不冷？', localAsk: '你觉着冷不冷？' },
        { standardAsk: '您还有什么想说的吗？', localAsk: '你还有啥想说的？' }
      ],

      confusions: [
        { heard: '该', shouldBe: '街', note: '关中话"街"读 gāi' },
        { heard: '哈', shouldBe: '下', note: '关中话"下"读 hà' },
        { heard: '孩', shouldBe: '鞋', note: '关中话"鞋"读 hái' },
        { heard: '碾', shouldBe: '眼', note: '关中话部分 y 声母字读 n' },
        { heard: '鸟', shouldBe: '咬', note: '关中话"咬"读 niǎo' },
        { heard: '了', shouldBe: '咧', note: '关中话句末常说"咧"' },
        { heard: '片', shouldBe: '谝', note: '"谝"（聊天）读 piǎn' },
        { heard: '跌', shouldBe: '咥', note: '"咥"（吃）读 dié' },
        { heard: '撒', shouldBe: '啥', note: '关中话"啥"读 sà' },
        { heard: '个就', shouldBe: '圪蹴', note: '"圪蹴"（蹲）读 gējiu' },
        { heard: '改', shouldBe: '解', note: '关中话"解"读 gǎi' },
        { heard: '辽', shouldBe: '嫽', note: '"嫽"（好）读 liáo' }
      ],

      flavor: ['咧', '啥', '咥', '谝', '嫽', '美', '碎', '怂', '么', '圪蹴']
    },

    {
      id: 'tianjin',
      name: '天津话',
      area: '天津市',
      speechLang: 'zh-CN',
      speechNote: '普通话听写基本能认，"介、揍、嘛"这类字容易听错。',

      lexicon: [
        { dialect: '嘛', standard: '什么', note: '干嘛=干什么' },
        { dialect: '干嘛', standard: '干什么', note: '' },
        { dialect: '介', standard: '这', note: '' },
        { dialect: '介个', standard: '这个', note: '' },
        { dialect: '揍', standard: '做', note: '揍嘛=做什么' },
        { dialect: '揍嘛', standard: '干什么', note: '' },
        { dialect: '哏儿', standard: '有趣、幽默', note: '' },
        { dialect: '倍儿', standard: '非常、特别', note: '倍儿好=特别好' },
        { dialect: '齁', standard: '太（多形容味道重）', note: '齁咸=太咸' },
        { dialect: '白话', standard: '聊天', note: '' },
        { dialect: '贫', standard: '话多、嘴碎', note: '' },
        { dialect: '腻歪', standard: '黏人、让人烦', note: '' },
        { dialect: '伍的', standard: '什么的、之类的', note: '买点菜伍的' },
        { dialect: '果子', standard: '油条', note: '' },
        { dialect: '煎饼馃子', standard: '煎饼果子', note: '' },
        { dialect: '嘎巴菜', standard: '锅巴菜（天津小吃）', note: '' },
        { dialect: '遛弯', standard: '散步', note: '' },
        { dialect: '溜达', standard: '散步、随便走走', note: '' },
        { dialect: '待见', standard: '喜欢、看得上', note: '不待见=不喜欢' },
        { dialect: '眼力见儿', standard: '察言观色的本事', note: '' },
        { dialect: '逗闷子', standard: '开玩笑、解闷', note: '' },
        { dialect: '瓷实', standard: '结实、扎实', note: '' },
        { dialect: '得劲儿', standard: '舒服、合适', note: '' },
        { dialect: '舒坦', standard: '舒服', note: '' },
        { dialect: '幺蛾子', standard: '鬼点子、花招', note: '' },
        { dialect: '玩意儿', standard: '东西、物件', note: '' },
        { dialect: '家什', standard: '工具、用具', note: '' },
        { dialect: '胰子', standard: '肥皂', note: '老说法' },
        { dialect: '洋火', standard: '火柴', note: '老说法' },
        { dialect: '墩布', standard: '拖把', note: '' },
        { dialect: '归置', standard: '收拾、整理', note: '' },
        { dialect: '拾掇', standard: '收拾', note: '' },
        { dialect: '鼓捣', standard: '摆弄、折腾', note: '' },
        { dialect: '挨呲儿', standard: '挨批评', note: '' },
        { dialect: '蔫', standard: '没精神、不活跃', note: '' },
        { dialect: '肉', standard: '磨蹭、动作慢', note: '' },
        { dialect: '轴', standard: '固执、认死理', note: '' },
        { dialect: '摆谱', standard: '摆架子', note: '' },
        { dialect: '显摆', standard: '炫耀', note: '' },
        { dialect: '估摸', standard: '估计、琢磨', note: '' },
        { dialect: '爷们儿', standard: '男人、丈夫', note: '' },
        { dialect: '搁', standard: '放、放在', note: '' }
      ],

      kinship: [
        { dialect: '大爷', standard: '伯父（父亲的哥哥）', note: '' },
        { dialect: '大娘', standard: '伯母', note: '' },
        { dialect: '叔', standard: '叔叔', note: '' },
        { dialect: '婶子', standard: '婶婶', note: '' },
        { dialect: '姑', standard: '姑姑', note: '' },
        { dialect: '姨', standard: '姨妈', note: '' },
        { dialect: '舅', standard: '舅舅', note: '' },
        { dialect: '姥爷', standard: '外祖父', note: '' },
        { dialect: '姥姥', standard: '外祖母', note: '' },
        { dialect: '姑爷', standard: '女婿', note: '' },
        { dialect: '大伯子', standard: '丈夫的哥哥', note: '' },
        { dialect: '小叔子', standard: '丈夫的弟弟', note: '' },
        { dialect: '大姑子', standard: '丈夫的姐姐', note: '' },
        { dialect: '小姑子', standard: '丈夫的妹妹', note: '' },
        { dialect: '大姨子', standard: '妻子的姐姐', note: '' },
        { dialect: '小姨子', standard: '妻子的妹妹', note: '' },
        { dialect: '外甥', standard: '姐妹的儿子', note: '' },
        { dialect: '侄子', standard: '兄弟的儿子', note: '' }
      ],

      askForms: [
        { standardAsk: '您小时候最愿意吃啥饭？', localAsk: '您小时候最待见吃嘛饭？' },
        { standardAsk: '您家住在哪儿？', localAsk: '您家在嘛地方？' },
        { standardAsk: '您平时干什么？', localAsk: '您平时都揍嘛？' },
        { standardAsk: '您身体怎么样？', localAsk: '您身子骨怎么样？' },
        { standardAsk: '您昨天去哪儿了？', localAsk: '您昨儿个上哪儿去了？' },
        { standardAsk: '您晚上几点睡？', localAsk: '您晚上几点睡？' },
        { standardAsk: '您小时候上过学吗？', localAsk: '您小时候念过书吗？' },
        { standardAsk: '您有几个孩子？', localAsk: '您家几个孩子？' },
        { standardAsk: '您是什么时候结婚的？', localAsk: '您嘛时候结的婚？' },
        { standardAsk: '您觉得那时候日子苦吗？', localAsk: '您觉着那会儿日子苦不苦？' },
        { standardAsk: '您平时和谁聊天？', localAsk: '您平时跟谁白话白话？' },
        { standardAsk: '您愿意给我讲讲您的事吗？', localAsk: '您乐意跟我说说吗？' },
        { standardAsk: '您还记得小时候的事吗？', localAsk: '您还记着小时候的事儿吗？' },
        { standardAsk: '您喜欢吃什么？', localAsk: '您待见吃嘛？' },
        { standardAsk: '您冷不冷？', localAsk: '您觉着冷吗？' },
        { standardAsk: '您平时爱干什么？', localAsk: '您平时爱干嘛？' }
      ],

      confusions: [
        { heard: '吗', shouldBe: '嘛', note: '天津话句末常用"嘛"' },
        { heard: '这', shouldBe: '介', note: '天津话"这"读"介"' },
        { heard: '做', shouldBe: '揍', note: '天津话"做"读"揍"' },
        { heard: '猴', shouldBe: '齁', note: '"齁咸"的"齁"' },
        { heard: '根儿', shouldBe: '哏儿', note: '"哏儿"（有趣）读 gér' },
        { heard: '背', shouldBe: '倍儿', note: '"倍儿好"的"倍儿"' },
        { heard: '什么', shouldBe: '嘛', note: '天津话"什么"常说"嘛"' },
        { heard: '能', shouldBe: '弄', note: '天津话"弄"读 nèng' },
        { heard: '疵', shouldBe: '呲儿', note: '"呲儿"指训斥、数落' },
        { heard: '割', shouldBe: '搁', note: '"搁"是放的意思' },
        { heard: '倒饬', shouldBe: '捯饬', note: '"捯饬"指打扮、收拾' },
        { heard: '溜弯', shouldBe: '遛弯', note: '"遛弯"指散步' }
      ],

      flavor: ['嘛', '介', '哏儿', '倍儿', '齁', '揍', '腻歪', '白话', '得嘞', '玩意儿']
    },

    {
      id: 'chuanyu',
      name: '川渝话',
      area: '四川、重庆',
      speechLang: 'zh-CN',
      speechNote: '普通话听写能认出大意，平翘舌、前后鼻音不分，土话容易听错。',

      lexicon: [
        { dialect: '安逸', standard: '舒服、好', note: '' },
        { dialect: '巴适', standard: '好、舒服、妥帖', note: '' },
        { dialect: '摆龙门阵', standard: '聊天、闲聊', note: '' },
        { dialect: '耍', standard: '玩', note: '' },
        { dialect: '要得', standard: '行、可以', note: '' },
        { dialect: '要不得', standard: '不行', note: '' },
        { dialect: '啥子', standard: '什么', note: '' },
        { dialect: '咋个', standard: '怎么', note: '' },
        { dialect: '莫得', standard: '没有', note: '' },
        { dialect: '晓得', standard: '知道', note: '' },
        { dialect: '一哈', standard: '一下、一会儿', note: '等一哈=等一下' },
        { dialect: '好多', standard: '多少', note: '好多钱=多少钱' },
        { dialect: '好久', standard: '多久', note: '' },
        { dialect: '屋头', standard: '家里', note: '' },
        { dialect: '婆娘', standard: '老婆', note: '' },
        { dialect: '老汉儿', standard: '爸爸', note: '' },
        { dialect: '幺儿', standard: '最小的儿子；对孩子的昵称', note: '' },
        { dialect: '幺妹儿', standard: '最小的妹妹；对姑娘的称呼', note: '' },
        { dialect: '娃儿', standard: '孩子', note: '' },
        { dialect: '背篼', standard: '背篓', note: '' },
        { dialect: '栽秧', standard: '插秧', note: '' },
        { dialect: '谷子', standard: '稻谷', note: '' },
        { dialect: '打谷子', standard: '收割稻谷脱粒', note: '' },
        { dialect: '红苕', standard: '红薯', note: '' },
        { dialect: '洋芋', standard: '土豆', note: '' },
        { dialect: '苞谷', standard: '玉米', note: '' },
        { dialect: '胡豆', standard: '蚕豆', note: '' },
        { dialect: '海椒', standard: '辣椒', note: '' },
        { dialect: '藤藤菜', standard: '空心菜', note: '' },
        { dialect: '折耳根', standard: '鱼腥草（凉拌菜）', note: '' },
        { dialect: '粑粑', standard: '饼类、糕点', note: '' },
        { dialect: '糍粑', standard: '糯米做成的粑', note: '' },
        { dialect: '醪糟', standard: '糯米酒酿', note: '' },
        { dialect: '豆花', standard: '豆花、嫩豆腐', note: '' },
        { dialect: '抄手', standard: '馄饨', note: '' },
        { dialect: '坝子', standard: '平地、场院', note: '' },
        { dialect: '田坎', standard: '田埂', note: '' },
        { dialect: '赶场', standard: '赶集', note: '' },
        { dialect: '走人户', standard: '走亲戚', note: '' },
        { dialect: '坐席', standard: '赴宴、吃酒席', note: '' },
        { dialect: '扯皮', standard: '吵架、闹纠纷', note: '' },
        { dialect: '吼', standard: '大声喊、嚷', note: '' },
        { dialect: '恼火', standard: '严重、麻烦、累', note: '' },
        { dialect: '造孽', standard: '可怜', note: '' },
        { dialect: '撇脱', standard: '干脆、利索', note: '' },
        { dialect: '二天', standard: '改天、以后', note: '' },
        { dialect: '拢', standard: '到、到达', note: '拢了=到了' },
        { dialect: '转来', standard: '回来', note: '' },
        { dialect: '歇气', standard: '休息', note: '' },
        { dialect: '帕子', standard: '毛巾', note: '' },
        { dialect: '撮箕', standard: '簸箕', note: '' },
        { dialect: '甑子', standard: '蒸饭用的木桶', note: '' },
        { dialect: '瓜娃子', standard: '傻孩子', note: '戏称' },
        { dialect: '宝器', standard: '憨傻的人', note: '戏称' }
      ],

      kinship: [
        { dialect: '老汉儿', standard: '爸爸', note: '' },
        { dialect: '婆婆', standard: '奶奶', note: '' },
        { dialect: '爷爷', standard: '爷爷', note: '' },
        { dialect: '外公', standard: '外公', note: '' },
        { dialect: '外婆', standard: '外婆', note: '' },
        { dialect: '幺爸', standard: '最小的叔叔', note: '' },
        { dialect: '幺姑', standard: '最小的姑姑', note: '' },
        { dialect: '幺舅', standard: '最小的舅舅', note: '' },
        { dialect: '舅娘', standard: '舅妈', note: '' },
        { dialect: '孃孃', standard: '姑姑；也泛称阿姨', note: '' },
        { dialect: '幺儿', standard: '最小的儿子', note: '' },
        { dialect: '幺女', standard: '最小的女儿', note: '' },
        { dialect: '幺妹儿', standard: '最小的妹妹', note: '' },
        { dialect: '舅子', standard: '妻子的兄弟', note: '' },
        { dialect: '老挑', standard: '连襟', note: '妻子的姐妹的丈夫' },
        { dialect: '兄弟', standard: '弟弟', note: '' },
        { dialect: '娃儿', standard: '孩子', note: '' }
      ],

      askForms: [
        { standardAsk: '您小时候最愿意吃啥饭？', localAsk: '您小时候最喜欢吃啥子饭？' },
        { standardAsk: '您家住在哪儿？', localAsk: '您屋头在哪儿？' },
        { standardAsk: '您平时干什么？', localAsk: '您平时都做啥子？' },
        { standardAsk: '您身体怎么样？', localAsk: '您身体咋个样？' },
        { standardAsk: '您昨天去哪儿了？', localAsk: '您昨天到哪儿去了？' },
        { standardAsk: '您晚上几点睡？', localAsk: '您晚上几点睡的？' },
        { standardAsk: '您小时候上过学吗？', localAsk: '您小时候读过书没得？' },
        { standardAsk: '您有几个孩子？', localAsk: '您有几个娃儿？' },
        { standardAsk: '您是什么时候结婚的？', localAsk: '您啥子时候结的婚？' },
        { standardAsk: '您觉得那时候日子苦吗？', localAsk: '您觉得那阵子日子苦不苦？' },
        { standardAsk: '您平时和谁聊天？', localAsk: '您平时跟哪个摆龙门阵？' },
        { standardAsk: '您愿意给我讲讲您的事吗？', localAsk: '您愿不愿意跟我摆一哈？' },
        { standardAsk: '您还记得小时候的事吗？', localAsk: '您还记得不？' },
        { standardAsk: '您喜欢吃什么？', localAsk: '您喜欢吃啥子？' },
        { standardAsk: '您冷不冷？', localAsk: '您觉不觉得冷？' },
        { standardAsk: '您还有什么想说的吗？', localAsk: '您还有啥子想说的？' }
      ],

      confusions: [
        { heard: '兰', shouldBe: '男', note: '川渝 n/l 不分' },
        { heard: '拉', shouldBe: '拿', note: '川渝 n/l 不分' },
        { heard: '森', shouldBe: '生', note: '前后鼻音不分' },
        { heard: '陈', shouldBe: '程', note: '前后鼻音不分' },
        { heard: '丝', shouldBe: '诗', note: '平翘舌不分' },
        { heard: '四', shouldBe: '是', note: '平翘舌不分' },
        { heard: '呲', shouldBe: '吃', note: '平翘舌不分' },
        { heard: '恩', shouldBe: '硬', note: '川渝话"硬"读 èn' },
        { heard: '啥', shouldBe: '啥子', note: '川渝话常说"啥子"' },
        { heard: '一下', shouldBe: '一哈', note: '"一哈"是一会儿、一下' },
        { heard: '吗', shouldBe: '嘛', note: '句末语气词"嘛"' },
        { heard: '没得', shouldBe: '莫得', note: '"莫得"是没有的意思' }
      ],

      flavor: ['安逸', '巴适', '要得', '耍', '莫得', '晓得', '啥子', '咋个', '嘛', '哈']
    },

    {
      id: 'shandong',
      name: '山东话',
      area: '山东省',
      speechLang: 'zh-CN',
      speechNote: '普通话听写基本能认，"俺、恁、哈"这类字容易听错。',

      lexicon: [
        { dialect: '俺', standard: '我', note: '' },
        { dialect: '咱', standard: '我们', note: '' },
        { dialect: '恁', standard: '你们', note: '' },
        { dialect: '么', standard: '什么', note: '干么=干什么' },
        { dialect: '干么', standard: '干什么', note: '' },
        { dialect: '哈', standard: '喝', note: '哈水=喝水' },
        { dialect: '饽饽', standard: '馒头', note: '' },
        { dialect: '煎饼', standard: '摊烙的薄饼（主食）', note: '' },
        { dialect: '扁食', standard: '饺子', note: '' },
        { dialect: '糊涂', standard: '玉米面粥', note: '' },
        { dialect: '地瓜', standard: '红薯', note: '' },
        { dialect: '地蛋', standard: '土豆', note: '' },
        { dialect: '火烧', standard: '烧饼', note: '' },
        { dialect: '芫荽', standard: '香菜', note: '' },
        { dialect: '大酱', standard: '黄豆酱', note: '' },
        { dialect: '棒子', standard: '玉米', note: '' },
        { dialect: '鏊子', standard: '烙煎饼用的平底铁锅', note: '' },
        { dialect: '碌碡', standard: '打场用的石磙', note: '' },
        { dialect: '耩地', standard: '用耧播种', note: '' },
        { dialect: '地排车', standard: '平板车', note: '' },
        { dialect: '风箱', standard: '生火用的鼓风箱', note: '' },
        { dialect: '水筲', standard: '水桶', note: '' },
        { dialect: '手巾', standard: '毛巾', note: '' },
        { dialect: '胰子', standard: '肥皂', note: '老说法' },
        { dialect: '洋火', standard: '火柴', note: '老说法' },
        { dialect: '褂子', standard: '上衣', note: '' },
        { dialect: '后晌', standard: '下午', note: '' },
        { dialect: '夜来', standard: '昨天', note: '' },
        { dialect: '对子', standard: '春联', note: '贴对子=贴春联' },
        { dialect: '拉呱', standard: '聊天', note: '' },
        { dialect: '实诚', standard: '实在、厚道', note: '' },
        { dialect: '打谱', standard: '打算', note: '' },
        { dialect: '寻思', standard: '想、琢磨', note: '' },
        { dialect: '合计', standard: '商量', note: '' },
        { dialect: '中', standard: '行、可以', note: '' },
        { dialect: '不中', standard: '不行', note: '' },
        { dialect: '怵', standard: '害怕、发怵', note: '' },
        { dialect: '打怵', standard: '害怕', note: '' },
        { dialect: '紧巴', standard: '日子紧、拮据', note: '' },
        { dialect: '宽绰', standard: '宽裕', note: '' },
        { dialect: '凑付', standard: '凑合、将就', note: '' },
        { dialect: '熊', standard: '训斥、批评', note: '熊了一顿' },
        { dialect: '板正', standard: '整齐、规矩', note: '' },
        { dialect: '恣', standard: '高兴、舒服', note: '' },
        { dialect: '怪', standard: '很、挺', note: '怪好=挺好' },
        { dialect: '孬', standard: '差、坏', note: '' },
        { dialect: '拾掇', standard: '收拾', note: '' }
      ],

      kinship: [
        { dialect: '大爷', standard: '伯父（父亲的哥哥）', note: '' },
        { dialect: '大娘', standard: '伯母', note: '' },
        { dialect: '婶子', standard: '婶婶', note: '' },
        { dialect: '妗子', standard: '舅妈', note: '' },
        { dialect: '姥爷', standard: '外祖父', note: '' },
        { dialect: '姥姥', standard: '外祖母', note: '' },
        { dialect: '娘', standard: '妈妈', note: '' },
        { dialect: '兄弟', standard: '弟弟', note: '' },
        { dialect: '姊妹', standard: '姐妹', note: '' },
        { dialect: '闺女', standard: '女儿', note: '' },
        { dialect: '小子', standard: '儿子、男孩', note: '' },
        { dialect: '媳妇', standard: '妻子', note: '' },
        { dialect: '姑爷', standard: '女婿', note: '' },
        { dialect: '丈人', standard: '岳父', note: '' },
        { dialect: '丈母娘', standard: '岳母', note: '' },
        { dialect: '外甥', standard: '姐妹的儿子', note: '' },
        { dialect: '侄子', standard: '兄弟的儿子', note: '' }
      ],

      askForms: [
        { standardAsk: '您小时候最愿意吃啥饭？', localAsk: '您小时候最爱吃啥饭？' },
        { standardAsk: '您家住在哪儿？', localAsk: '您家在哪住？' },
        { standardAsk: '您平时干什么？', localAsk: '您平时干么？' },
        { standardAsk: '您身体怎么样？', localAsk: '您身体咋样？' },
        { standardAsk: '您昨天去哪儿了？', localAsk: '您夜来上哪去了？' },
        { standardAsk: '您晚上几点睡？', localAsk: '您晚上几点睡下的？' },
        { standardAsk: '您小时候上过学吗？', localAsk: '您小时候念过书没？' },
        { standardAsk: '您有几个孩子？', localAsk: '您家里有几个孩子？' },
        { standardAsk: '您是什么时候结婚的？', localAsk: '您啥时候结的婚？' },
        { standardAsk: '您觉得那时候日子苦吗？', localAsk: '您觉着那阵子日子苦不苦？' },
        { standardAsk: '您平时和谁聊天？', localAsk: '您平时跟谁拉呱？' },
        { standardAsk: '您愿意给我讲讲您的事吗？', localAsk: '您愿意跟俺拉拉不？' },
        { standardAsk: '您还记得小时候的事吗？', localAsk: '您还记得不？' },
        { standardAsk: '您喜欢吃什么？', localAsk: '您愿意吃啥？' },
        { standardAsk: '您冷不冷？', localAsk: '您觉着冷不冷？' },
        { standardAsk: '您还有什么想说的吗？', localAsk: '您还有啥想说的？' }
      ],

      confusions: [
        { heard: '您', shouldBe: '恁', note: '山东话"你们"说"恁"' },
        { heard: '干嘛', shouldBe: '干么', note: '"么"是"什么"的土说法' },
        { heard: '喝', shouldBe: '哈', note: '山东话"喝"说"哈"' },
        { heard: '人', shouldBe: '银', note: '胶东部分地区 r 读成 y' },
        { heard: '又', shouldBe: '肉', note: '胶东部分地区 r 读成 y' },
        { heard: '夜', shouldBe: '热', note: '胶东部分地区 r 读成 y' },
        { heard: '滋', shouldBe: '恣', note: '"恣"是高兴、舒服的意思' },
        { heard: '勃勃', shouldBe: '饽饽', note: '"饽饽"是馒头' },
        { heard: '讲地', shouldBe: '耩地', note: '"耩地"是用耧播种' },
        { heard: '蒿', shouldBe: '薅', note: '"薅"是拔（草）' },
        { heard: '顿', shouldBe: '扽', note: '"扽"是拽、拉' },
        { heard: '响午', shouldBe: '晌午', note: '"晌午"是中午' }
      ],

      flavor: ['俺', '咱', '恁', '中', '怪', '恣', '拉呱', '么', '哈', '寻思']
    },

    {
      id: 'henan',
      name: '河南话',
      area: '河南省',
      speechLang: 'zh-CN',
      speechNote: '普通话听写基本能认，前后鼻音、平翘舌不分，土话容易听错。',

      lexicon: [
        { dialect: '中', standard: '行、可以', note: '' },
        { dialect: '中不中', standard: '行不行', note: '' },
        { dialect: '不中', standard: '不行', note: '' },
        { dialect: '得劲', standard: '舒服、好', note: '' },
        { dialect: '弄啥', standard: '干什么', note: '' },
        { dialect: '啥', standard: '什么', note: '' },
        { dialect: '咋', standard: '怎么', note: '' },
        { dialect: '咋了', standard: '怎么了', note: '' },
        { dialect: '白', standard: '别、不要', note: '白说了=别说了' },
        { dialect: '嘞', standard: '的、了（语气词）', note: '' },
        { dialect: '恁', standard: '那么、这么', note: '恁大=那么大' },
        { dialect: '俺', standard: '我', note: '' },
        { dialect: '咱', standard: '我们', note: '' },
        { dialect: '妞', standard: '女儿、女孩子', note: '' },
        { dialect: '孩儿', standard: '孩子', note: '' },
        { dialect: '媳妇儿', standard: '妻子', note: '' },
        { dialect: '吃嘴', standard: '嘴馋', note: '' },
        { dialect: '坐桌', standard: '赴宴、吃酒席', note: '' },
        { dialect: '喝汤', standard: '吃晚饭', note: '部分地区把吃晚饭叫喝汤' },
        { dialect: '馍', standard: '馒头', note: '' },
        { dialect: '蒸馍', standard: '蒸馒头', note: '' },
        { dialect: '烙馍', standard: '烙饼', note: '' },
        { dialect: '烩面', standard: '烩面（河南面食）', note: '' },
        { dialect: '胡辣汤', standard: '胡辣汤（河南小吃）', note: '' },
        { dialect: '扁食', standard: '饺子', note: '' },
        { dialect: '窝窝头', standard: '玉米面窝头', note: '' },
        { dialect: '谷子', standard: '粟、小米', note: '' },
        { dialect: '薅', standard: '拔', note: '' },
        { dialect: '牲口', standard: '牲畜', note: '' },
        { dialect: '架子车', standard: '平板车', note: '' },
        { dialect: '纺车', standard: '纺线的车', note: '' },
        { dialect: '手巾', standard: '毛巾', note: '' },
        { dialect: '胰子', standard: '肥皂', note: '老说法' },
        { dialect: '洋火', standard: '火柴', note: '老说法' },
        { dialect: '对子', standard: '春联', note: '' },
        { dialect: '面叶儿', standard: '面片（面食）', note: '' },
        { dialect: '堂屋', standard: '正房、客厅', note: '' },
        { dialect: '灶火', standard: '厨房', note: '' },
        { dialect: '茅房', standard: '厕所', note: '' },
        { dialect: '柴火垛', standard: '柴火堆', note: '' },
        { dialect: '麦秸垛', standard: '麦秆堆', note: '' },
        { dialect: '麸子', standard: '麦麸', note: '' },
        { dialect: '辘轳', standard: '井上绞水用的工具', note: '' },
        { dialect: '石磨', standard: '磨粮食的石磨', note: '' },
        { dialect: '石磙', standard: '打场用的石滚子', note: '' },
        { dialect: '搓板', standard: '搓衣板', note: '' },
        { dialect: '顶针', standard: '做针线活用的顶针', note: '' },
        { dialect: '纳鞋底', standard: '做布鞋底', note: '' },
        { dialect: '喷空儿', standard: '聊天、闲聊', note: '' },
        { dialect: '晌午', standard: '中午', note: '' },
        { dialect: '早起', standard: '早晨', note: '' },
        { dialect: '搁', standard: '放、放在', note: '' },
        { dialect: '撂', standard: '放下', note: '' },
        { dialect: '仨', standard: '三个', note: '' },
        { dialect: '俩', standard: '两个', note: '' }
      ],

      kinship: [
        { dialect: '大爷', standard: '伯父（父亲的哥哥）', note: '' },
        { dialect: '大娘', standard: '伯母', note: '' },
        { dialect: '婶子', standard: '婶婶', note: '' },
        { dialect: '妗子', standard: '舅妈', note: '' },
        { dialect: '姥爷', standard: '外祖父', note: '' },
        { dialect: '姥姥', standard: '外祖母', note: '' },
        { dialect: '爹', standard: '爸爸', note: '' },
        { dialect: '娘', standard: '妈妈', note: '' },
        { dialect: '兄弟', standard: '弟弟', note: '' },
        { dialect: '姊妹', standard: '姐妹', note: '' },
        { dialect: '闺女', standard: '女儿', note: '' },
        { dialect: '小子', standard: '儿子、男孩', note: '' },
        { dialect: '媳妇儿', standard: '妻子', note: '' },
        { dialect: '老表', standard: '表兄弟', note: '' },
        { dialect: '丈人', standard: '岳父', note: '' },
        { dialect: '丈母娘', standard: '岳母', note: '' },
        { dialect: '姑爷', standard: '女婿', note: '' },
        { dialect: '外甥', standard: '姐妹的儿子', note: '' }
      ],

      askForms: [
        { standardAsk: '您小时候最愿意吃啥饭？', localAsk: '您小时候最爱吃啥饭？' },
        { standardAsk: '您家住在哪儿？', localAsk: '您家在哪住？' },
        { standardAsk: '您平时干什么？', localAsk: '您平时都弄啥嘞？' },
        { standardAsk: '您身体怎么样？', localAsk: '您身体咋样？' },
        { standardAsk: '您昨天去哪儿了？', localAsk: '您昨天上哪去了？' },
        { standardAsk: '您晚上几点睡？', localAsk: '您晚上几点睡？' },
        { standardAsk: '您小时候上过学吗？', localAsk: '您小时候念过书没有？' },
        { standardAsk: '您有几个孩子？', localAsk: '您有几个孩儿？' },
        { standardAsk: '您是什么时候结婚的？', localAsk: '您啥时候结的婚？' },
        { standardAsk: '您觉得那时候日子苦吗？', localAsk: '您觉着那会儿日子苦不苦？' },
        { standardAsk: '您平时和谁聊天？', localAsk: '您平时跟谁喷空儿？' },
        { standardAsk: '您愿意给我讲讲您的事吗？', localAsk: '您愿意跟俺说说不？' },
        { standardAsk: '您还记得小时候的事吗？', localAsk: '您还记得不？' },
        { standardAsk: '您喜欢吃什么？', localAsk: '您愿意吃啥？' },
        { standardAsk: '您冷不冷？', localAsk: '您觉着冷不冷？' },
        { standardAsk: '您还有什么想说的吗？', localAsk: '您还有啥想说的？' }
      ],

      confusions: [
        { heard: '别', shouldBe: '白', note: '河南话"别"说"白"' },
        { heard: '了', shouldBe: '嘞', note: '句末语气词常说"嘞"' },
        { heard: '呢', shouldBe: '嘞', note: '句末语气词常说"嘞"' },
        { heard: '森', shouldBe: '生', note: '前后鼻音不分' },
        { heard: '陈', shouldBe: '程', note: '前后鼻音不分' },
        { heard: '新', shouldBe: '星', note: '前后鼻音不分' },
        { heard: '民', shouldBe: '明', note: '前后鼻音不分' },
        { heard: '嫩', shouldBe: '恁', note: '"恁"是那么、这么的意思' },
        { heard: '喷空', shouldBe: '喷空儿', note: '"喷空儿"是聊天' },
        { heard: '三', shouldBe: '仨', note: '"仨"是三个' },
        { heard: '两', shouldBe: '俩', note: '"俩"是两个' },
        { heard: '割', shouldBe: '搁', note: '"搁"是放的意思' }
      ],

      flavor: ['中', '得劲', '咋', '啥', '嘞', '白', '俺', '咱', '恁', '弄啥']
    },

    {
      id: 'yue',
      name: '粤语（广府）',
      area: '广东珠三角、香港、澳门',
      speechLang: 'zh-HK',
      speechNote: '粤语听写基本能认，但同音字多，需要家人帮忙挑字。',

      lexicon: [
        { dialect: '食饭', standard: '吃饭', note: '' },
        { dialect: '食', standard: '吃', note: '' },
        { dialect: '饮', standard: '喝', note: '' },
        { dialect: '瞓觉', standard: '睡觉', note: '' },
        { dialect: '瞓', standard: '睡', note: '' },
        { dialect: '冲凉', standard: '洗澡', note: '' },
        { dialect: '返工', standard: '上班', note: '' },
        { dialect: '返屋企', standard: '回家', note: '' },
        { dialect: '屋企', standard: '家', note: '' },
        { dialect: '睇', standard: '看', note: '' },
        { dialect: '听日', standard: '明天', note: '' },
        { dialect: '琴日', standard: '昨天', note: '' },
        { dialect: '而家', standard: '现在', note: '' },
        { dialect: '旧时', standard: '从前', note: '' },
        { dialect: '第日', standard: '改天、以后', note: '' },
        { dialect: '好耐', standard: '很久', note: '' },
        { dialect: '冇', standard: '没有', note: '' },
        { dialect: '唔', standard: '不', note: '' },
        { dialect: '唔使', standard: '不用', note: '' },
        { dialect: '唔得', standard: '不行', note: '' },
        { dialect: '得闲', standard: '有空', note: '' },
        { dialect: '倾偈', standard: '聊天', note: '' },
        { dialect: '吹水', standard: '闲聊、吹牛', note: '' },
        { dialect: '食烟', standard: '抽烟', note: '' },
        { dialect: '饮茶', standard: '喝茶、吃早茶', note: '' },
        { dialect: '煲汤', standard: '炖汤', note: '' },
        { dialect: '餸', standard: '菜（下饭的菜）', note: '' },
        { dialect: '肠粉', standard: '肠粉（小吃）', note: '' },
        { dialect: '云吞面', standard: '馄饨面', note: '' },
        { dialect: '烧鹅', standard: '烧鹅（烧味）', note: '' },
        { dialect: '叉烧', standard: '叉烧肉', note: '' },
        { dialect: '豉油', standard: '酱油', note: '' },
        { dialect: '油炸鬼', standard: '油条', note: '' },
        { dialect: '冷衫', standard: '毛衣', note: '' },
        { dialect: '薯仔', standard: '土豆', note: '' },
        { dialect: '粟米', standard: '玉米', note: '' },
        { dialect: '芫茜', standard: '香菜', note: '' },
        { dialect: '马蹄', standard: '荸荠', note: '' },
        { dialect: '银纸', standard: '钞票、钱', note: '' },
        { dialect: '毫子', standard: '硬币', note: '' },
        { dialect: '糖水', standard: '甜汤、甜品', note: '' },
        { dialect: '糉', standard: '粽子', note: '' },
        { dialect: '出粮', standard: '发工资', note: '' },
        { dialect: '孤寒', standard: '吝啬、小气', note: '' },
        { dialect: '叻', standard: '能干、聪明', note: '' },
        { dialect: '利是', standard: '红包', note: '' },
        { dialect: '斟茶', standard: '倒茶', note: '' },
        { dialect: '睇医生', standard: '看病', note: '' },
        { dialect: '肚饿', standard: '饿', note: '' },
        { dialect: '攰', standard: '累', note: '' },
        { dialect: '行街', standard: '逛街', note: '' },
        { dialect: '行山', standard: '爬山', note: '' },
        { dialect: '游水', standard: '游泳', note: '' },
        { dialect: '捉棋', standard: '下棋', note: '' },
        { dialect: '打麻雀', standard: '打麻将', note: '' },
        { dialect: '睇戏', standard: '看戏、看电影', note: '' },
        { dialect: '大戏', standard: '粤剧', note: '' },
        { dialect: '游车河', standard: '坐车兜风', note: '' },
        { dialect: '拜山', standard: '扫墓', note: '' },
        { dialect: '行清', standard: '清明扫墓', note: '' },
        { dialect: '白事', standard: '丧事', note: '' },
        { dialect: '红事', standard: '喜事', note: '' },
        { dialect: '入伙', standard: '搬进新居', note: '' },
        { dialect: '做寿', standard: '过生日（祝寿）', note: '' }
      ],

      kinship: [
        { dialect: '阿爸', standard: '爸爸', note: '' },
        { dialect: '阿妈', standard: '妈妈', note: '' },
        { dialect: '爷爷', standard: '祖父', note: '' },
        { dialect: '嫲嫲', standard: '祖母', note: '' },
        { dialect: '阿公', standard: '外祖父', note: '' },
        { dialect: '阿婆', standard: '外祖母', note: '' },
        { dialect: '伯父', standard: '伯父', note: '' },
        { dialect: '伯娘', standard: '伯母', note: '' },
        { dialect: '叔父', standard: '叔叔', note: '' },
        { dialect: '婶母', standard: '婶婶', note: '' },
        { dialect: '姑妈', standard: '父亲的姐姐', note: '' },
        { dialect: '姑姐', standard: '父亲的妹妹', note: '' },
        { dialect: '舅父', standard: '舅舅', note: '' },
        { dialect: '舅母', standard: '舅妈', note: '' },
        { dialect: '姨妈', standard: '姨母', note: '' },
        { dialect: '姨丈', standard: '姨父', note: '' },
        { dialect: '家姐', standard: '姐姐', note: '' },
        { dialect: '细佬', standard: '弟弟', note: '' },
        { dialect: '细妹', standard: '妹妹', note: '' },
        { dialect: '大佬', standard: '哥哥', note: '' },
        { dialect: '新抱', standard: '儿媳', note: '' },
        { dialect: '老公', standard: '丈夫', note: '' },
        { dialect: '老婆', standard: '妻子', note: '' },
        { dialect: '外父', standard: '岳父', note: '' },
        { dialect: '外母', standard: '岳母', note: '' },
        { dialect: '家婆', standard: '婆婆（丈夫的母亲）', note: '' },
        { dialect: '仔', standard: '儿子', note: '' },
        { dialect: '女', standard: '女儿', note: '' },
        { dialect: '契仔', standard: '干儿子', note: '' },
        { dialect: '契女', standard: '干女儿', note: '' },
        { dialect: '舅仔', standard: '妻子的弟弟', note: '' },
        { dialect: '姨仔', standard: '妻子的妹妹', note: '' },
        { dialect: '叔仔', standard: '丈夫的弟弟', note: '' }
      ],

      askForms: [
        { standardAsk: '您小时候最愿意吃啥饭？', localAsk: '你细个嗰阵最中意食咩饭？' },
        { standardAsk: '您家住在哪儿？', localAsk: '你屋企喺边度？' },
        { standardAsk: '您平时干什么？', localAsk: '你平时做咩嘢？' },
        { standardAsk: '您身体怎么样？', localAsk: '你身体点样？' },
        { standardAsk: '您昨天去哪儿了？', localAsk: '你琴日去咗边度？' },
        { standardAsk: '您晚上几点睡？', localAsk: '你夜晚几点瞓？' },
        { standardAsk: '您小时候上过学吗？', localAsk: '你细个嗰阵有冇读书？' },
        { standardAsk: '您有几个孩子？', localAsk: '你有几个仔女？' },
        { standardAsk: '您是什么时候结婚的？', localAsk: '你几时结婚嘅？' },
        { standardAsk: '您觉得那时候日子苦吗？', localAsk: '你觉唔觉得嗰阵时日子辛唔辛苦？' },
        { standardAsk: '您平时和谁聊天？', localAsk: '你平时同边个倾偈？' },
        { standardAsk: '您愿意给我讲讲您的事吗？', localAsk: '你愿唔愿意讲俾我听？' },
        { standardAsk: '您还记得小时候的事吗？', localAsk: '你仲记唔记得？' },
        { standardAsk: '您喜欢吃什么？', localAsk: '你中意食啲咩？' },
        { standardAsk: '您冷不冷？', localAsk: '你觉唔觉得冻？' },
        { standardAsk: '您还有什么想说的吗？', localAsk: '你仲有咩想讲？' }
      ],

      confusions: [
        { heard: '係', shouldBe: '喺', note: '"喺"表示"在"（喺边度=在哪里）' },
        { heard: '系', shouldBe: '係', note: '"係"表示"是"' },
        { heard: '训', shouldBe: '瞓', note: '"瞓"表示"睡"' },
        { heard: '体', shouldBe: '睇', note: '"睇"表示"看"' },
        { heard: '吃', shouldBe: '食', note: '粤语"吃"说"食"' },
        { heard: '左', shouldBe: '咗', note: '"咗"是"了"的意思' },
        { heard: '野', shouldBe: '嘢', note: '"嘢"表示"东西"' },
        { heard: '个', shouldBe: '嗰', note: '"嗰"表示"那"（嗰阵=那时）' },
        { heard: '贵', shouldBe: '攰', note: '"攰"是累的意思' },
        { heard: '点', shouldBe: '掂', note: '"掂"是妥当、完成的意思' },
        { heard: '比', shouldBe: '畀', note: '"畀"是"给"的意思' },
        { heard: '稳', shouldBe: '揾', note: '"揾"是"找"的意思' },
        { heard: '拒', shouldBe: '佢', note: '"佢"是"他/她"' }
      ],

      flavor: ['唔', '冇', '咩', '嘅', '啦', '咯', '啩', '添', '㗎', '咋']
    },

    {
      id: 'wu',
      name: '吴语（苏沪）',
      area: '上海、苏州及周边',
      speechLang: 'zh-CN',
      speechNote: '吴语和普通话差别大，听写错误多，最需要家人协助纠错。',

      lexicon: [
        { dialect: '侬', standard: '你', note: '' },
        { dialect: '阿拉', standard: '我们', note: '' },
        { dialect: '伊', standard: '他、她', note: '' },
        { dialect: '伊拉', standard: '他们', note: '' },
        { dialect: '啥', standard: '什么', note: '' },
        { dialect: '物事', standard: '东西', note: '' },
        { dialect: '白相', standard: '玩', note: '' },
        { dialect: '汏浴', standard: '洗澡', note: '' },
        { dialect: '汏', standard: '洗', note: '汏衣裳=洗衣服' },
        { dialect: '衣裳', standard: '衣服', note: '' },
        { dialect: '困觉', standard: '睡觉', note: '' },
        { dialect: '困', standard: '睡', note: '' },
        { dialect: '吃茶', standard: '喝茶', note: '' },
        { dialect: '灶头', standard: '灶台', note: '' },
        { dialect: '镬子', standard: '锅', note: '' },
        { dialect: '镬盖', standard: '锅盖', note: '' },
        { dialect: '铲刀', standard: '锅铲', note: '' },
        { dialect: '调羹', standard: '勺子', note: '' },
        { dialect: '面盆', standard: '脸盆', note: '' },
        { dialect: '马桶', standard: '马桶（便桶）', note: '老物件' },
        { dialect: '茅坑', standard: '厕所', note: '' },
        { dialect: '掸帚', standard: '鸡毛掸子', note: '' },
        { dialect: '畚箕', standard: '簸箕', note: '' },
        { dialect: '揩布', standard: '抹布', note: '' },
        { dialect: '揩面', standard: '洗脸', note: '' },
        { dialect: '面孔', standard: '脸', note: '' },
        { dialect: '额角头', standard: '额头', note: '' },
        { dialect: '眼乌珠', standard: '眼珠', note: '' },
        { dialect: '鼻头', standard: '鼻子', note: '' },
        { dialect: '肩胛', standard: '肩膀', note: '' },
        { dialect: '背脊', standard: '后背', note: '' },
        { dialect: '肚皮', standard: '肚子', note: '' },
        { dialect: '脚馒头', standard: '膝盖', note: '' },
        { dialect: '剃头', standard: '理发', note: '' },
        { dialect: '看毛病', standard: '看病', note: '' },
        { dialect: '毛病', standard: '病', note: '' },
        { dialect: '发热', standard: '发烧', note: '' },
        { dialect: '伤风', standard: '感冒', note: '' },
        { dialect: '郎中', standard: '中医', note: '旧称' },
        { dialect: '落雨', standard: '下雨', note: '' },
        { dialect: '落雪', standard: '下雪', note: '' },
        { dialect: '热天', standard: '夏天', note: '' },
        { dialect: '冷天', standard: '冬天', note: '' },
        { dialect: '黄梅天', standard: '梅雨季节', note: '' },
        { dialect: '年脚边', standard: '年底', note: '' },
        { dialect: '压岁钿', standard: '压岁钱', note: '' },
        { dialect: '铜钿', standard: '钱', note: '' },
        { dialect: '钞票', standard: '钱（纸币）', note: '' },
        { dialect: '工钿', standard: '工资', note: '' },
        { dialect: '荡马路', standard: '逛街', note: '' },
        { dialect: '奔', standard: '跑', note: '' },
        { dialect: '摆', standard: '放', note: '' },
        { dialect: '掼', standard: '扔、摔', note: '' },
        { dialect: '拎', standard: '提', note: '' },
        { dialect: '吵相骂', standard: '吵架', note: '' },
        { dialect: '瞎三话四', standard: '胡说八道', note: '' },
        { dialect: '话', standard: '说', note: '' },
        { dialect: '晓得', standard: '知道', note: '' },
        { dialect: '勿', standard: '不', note: '' },
        { dialect: '呒没', standard: '没有', note: '' },
        { dialect: '覅', standard: '不要、别', note: '' },
        { dialect: '蛮', standard: '挺、很', note: '蛮好=挺好' },
        { dialect: '交关', standard: '很、非常多', note: '' },
        { dialect: '忒', standard: '太', note: '忒大=太大' },
        { dialect: '灵', standard: '好、棒', note: '' },
        { dialect: '来事', standard: '能干、有本事', note: '' },
        { dialect: '便当', standard: '方便', note: '' },
        { dialect: '推板', standard: '差', note: '' },
        { dialect: '蹩脚', standard: '差、质量不好', note: '' },
        { dialect: '戆', standard: '傻', note: '' },
        { dialect: '清爽', standard: '干净', note: '' },
        { dialect: '龌龊', standard: '脏', note: '' },
        { dialect: '适意', standard: '舒服', note: '' },
        { dialect: '惬意', standard: '舒服、愉快', note: '' },
        { dialect: '吃力', standard: '累', note: '' },
        { dialect: '打中觉', standard: '睡午觉', note: '' },
        { dialect: '夜饭', standard: '晚饭', note: '' },
        { dialect: '点心', standard: '糕点零食', note: '' },
        { dialect: '下饭', standard: '下饭的菜', note: '' },
        { dialect: '小菜', standard: '菜（菜肴）', note: '' },
        { dialect: '小笼馒头', standard: '小笼包', note: '' },
        { dialect: '生煎馒头', standard: '生煎包', note: '' },
        { dialect: '汤团', standard: '汤圆', note: '' },
        { dialect: '赤豆', standard: '红豆', note: '' },
        { dialect: '毛豆', standard: '带荚的鲜黄豆', note: '' },
        { dialect: '地栗', standard: '荸荠', note: '' },
        { dialect: '鸡毛菜', standard: '小白菜秧', note: '' },
        { dialect: '芋艿', standard: '芋头', note: '' },
        { dialect: '山芋', standard: '红薯', note: '' },
        { dialect: '洋山芋', standard: '土豆', note: '' },
        { dialect: '明朝', standard: '明天', note: '' },
        { dialect: '昨日', standard: '昨天', note: '' },
        { dialect: '前日', standard: '前天', note: '' },
        { dialect: '后日', standard: '后天', note: '' },
        { dialect: '日里', standard: '白天', note: '' },
        { dialect: '夜里', standard: '晚上', note: '' },
        { dialect: '晏', standard: '晚、迟', note: '' },
        { dialect: '勒海', standard: '在', note: '勒海屋里=在家里' }
      ],

      kinship: [
        { dialect: '阿爸', standard: '爸爸', note: '' },
        { dialect: '姆妈', standard: '妈妈', note: '' },
        { dialect: '爷', standard: '爸爸（背称）', note: '' },
        { dialect: '娘', standard: '妈妈（背称）', note: '' },
        { dialect: '阿爷', standard: '祖父', note: '' },
        { dialect: '阿奶', standard: '祖母', note: '' },
        { dialect: '外公', standard: '外祖父', note: '' },
        { dialect: '外婆', standard: '外祖母', note: '' },
        { dialect: '伯伯', standard: '伯父', note: '' },
        { dialect: '伯母', standard: '伯母', note: '' },
        { dialect: '叔叔', standard: '叔叔', note: '' },
        { dialect: '婶婶', standard: '婶婶', note: '' },
        { dialect: '姑妈', standard: '姑妈', note: '' },
        { dialect: '阿姨', standard: '姨妈', note: '' },
        { dialect: '舅舅', standard: '舅舅', note: '' },
        { dialect: '舅妈', standard: '舅妈', note: '' },
        { dialect: '阿哥', standard: '哥哥', note: '' },
        { dialect: '阿姐', standard: '姐姐', note: '' },
        { dialect: '阿弟', standard: '弟弟', note: '' },
        { dialect: '阿妹', standard: '妹妹', note: '' },
        { dialect: '老公', standard: '丈夫', note: '' },
        { dialect: '老婆', standard: '妻子', note: '' },
        { dialect: '家主婆', standard: '妻子', note: '' },
        { dialect: '男人', standard: '丈夫（口语）', note: '我男人=我丈夫' },
        { dialect: '女人', standard: '妻子（口语）', note: '我女人=我妻子' },
        { dialect: '小人', standard: '小孩、孩子', note: '' },
        { dialect: '小囡', standard: '小孩（也指女儿）', note: '' },
        { dialect: '囡', standard: '女儿、女孩', note: '' },
        { dialect: '女婿', standard: '女婿', note: '' },
        { dialect: '媳妇', standard: '儿媳', note: '' },
        { dialect: '阿侄', standard: '侄子', note: '' },
        { dialect: '孙子', standard: '孙子', note: '' },
        { dialect: '孙女', standard: '孙女', note: '' },
        { dialect: '外孙', standard: '外孙', note: '' },
        { dialect: '丈人', standard: '岳父', note: '' },
        { dialect: '丈母', standard: '岳母', note: '' }
      ],

      askForms: [
        { standardAsk: '您小时候最愿意吃啥饭？', localAsk: '侬小辰光最欢喜吃啥个饭？' },
        { standardAsk: '您家住在哪儿？', localAsk: '侬屋里勒啥地方？' },
        { standardAsk: '您平时干什么？', localAsk: '侬平常做点啥？' },
        { standardAsk: '您身体怎么样？', localAsk: '侬身体哪能？' },
        { standardAsk: '您昨天去哪儿了？', localAsk: '侬昨日到啥地方去了？' },
        { standardAsk: '您晚上几点睡？', localAsk: '侬夜里几点困觉？' },
        { standardAsk: '您小时候上过学吗？', localAsk: '侬小辰光读过书伐？' },
        { standardAsk: '您有几个孩子？', localAsk: '侬有几个小人？' },
        { standardAsk: '您是什么时候结婚的？', localAsk: '侬啥辰光结婚个？' },
        { standardAsk: '您觉得那时候日子苦吗？', localAsk: '侬觉着老早辰光日脚苦伐？' },
        { standardAsk: '您平时和谁聊天？', localAsk: '侬平常搭啥人讲闲话？' },
        { standardAsk: '您愿意给我讲讲您的事吗？', localAsk: '侬肯搭我讲讲伐？' },
        { standardAsk: '您还记得小时候的事吗？', localAsk: '侬还记得伐？' },
        { standardAsk: '您喜欢吃什么？', localAsk: '侬欢喜吃啥？' },
        { standardAsk: '您冷不冷？', localAsk: '侬觉着冷伐？' },
        { standardAsk: '您还有什么想说的吗？', localAsk: '侬还有啥想讲个？' }
      ],

      confusions: [
        { heard: '农', shouldBe: '侬', note: '"侬"是"你"' },
        { heard: '沙', shouldBe: '啥', note: '吴语"啥"读音近"沙"' },
        { heard: '不要', shouldBe: '覅', note: '"覅"是"不要"的合音' },
        { heard: '没有', shouldBe: '呒没', note: '"呒没"是"没有"' },
        { heard: '不', shouldBe: '勿', note: '吴语"不"常说"勿"' },
        { heard: '在海', shouldBe: '勒海', note: '"勒海"是"在"的意思' },
        { heard: '晨光', shouldBe: '辰光', note: '"辰光"是"时候"' },
        { heard: '锅子', shouldBe: '镬子', note: '"镬子"是"锅"' },
        { heard: '满好', shouldBe: '蛮好', note: '"蛮"是"挺、很"' },
        { heard: '特', shouldBe: '忒', note: '"忒"是"太"的意思' },
        { heard: '港', shouldBe: '戆', note: '"戆"是"傻"的意思' },
        { heard: '惯', shouldBe: '掼', note: '"掼"是"扔、摔"的意思' },
        { heard: '困告', shouldBe: '困觉', note: '"困觉"是"睡觉"' }
      ],

      flavor: ['侬', '阿拉', '啥', '勿', '蛮', '忒', '伐', '哉', '交关', '适意']
    },

    {
      id: 'putonghua',
      name: '普通话',
      area: '全国通用',
      speechLang: 'zh-CN',
      speechNote: '普通话听写识别率最高，个别同音字仍会出错。',

      lexicon: [
        { dialect: '干活', standard: '劳动、工作', note: '' },
        { dialect: '聊天', standard: '闲谈', note: '' },
        { dialect: '吃饭', standard: '用餐', note: '' },
        { dialect: '睡觉', standard: '睡眠', note: '' },
        { dialect: '生病', standard: '患病', note: '' }
      ],

      kinship: [
        { dialect: '爸爸', standard: '父亲', note: '' },
        { dialect: '妈妈', standard: '母亲', note: '' },
        { dialect: '爷爷', standard: '祖父', note: '' },
        { dialect: '奶奶', standard: '祖母', note: '' },
        { dialect: '外公', standard: '外祖父', note: '' },
        { dialect: '外婆', standard: '外祖母', note: '' },
        { dialect: '哥', standard: '哥哥', note: '' },
        { dialect: '姐', standard: '姐姐', note: '' },
        { dialect: '弟', standard: '弟弟', note: '' },
        { dialect: '妹', standard: '妹妹', note: '' },
        { dialect: '孩子', standard: '子女', note: '' },
        { dialect: '老伴', standard: '老年配偶', note: '' }
      ],

      askForms: [
        { standardAsk: '您小时候最喜欢吃什么？', localAsk: '您小时候最爱吃什么？' },
        { standardAsk: '您家住在哪儿？', localAsk: '您家住在哪儿？' },
        { standardAsk: '您平时做什么工作？', localAsk: '您平时干点什么活儿？' },
        { standardAsk: '您身体怎么样？', localAsk: '您身体还好吗？' },
        { standardAsk: '您昨天去哪儿了？', localAsk: '您昨天上哪儿去了？' },
        { standardAsk: '您晚上几点睡觉？', localAsk: '您晚上几点睡？' },
        { standardAsk: '您小时候上过学吗？', localAsk: '您小时候念过书吗？' },
        { standardAsk: '您有几个孩子？', localAsk: '您家几个孩子？' },
        { standardAsk: '您是什么时候结婚的？', localAsk: '您什么时候结的婚？' },
        { standardAsk: '您觉得那时候日子苦吗？', localAsk: '您觉得那会儿日子苦不苦？' },
        { standardAsk: '您平时和谁聊天？', localAsk: '您平时都跟谁聊天？' },
        { standardAsk: '您愿意给我讲讲您的事吗？', localAsk: '您愿意跟我讲讲您的事吗？' },
        { standardAsk: '您还记得小时候的事吗？', localAsk: '您还记得小时候的事儿吗？' },
        { standardAsk: '您喜欢吃什么菜？', localAsk: '您平时爱吃什么菜？' },
        { standardAsk: '您冷不冷？', localAsk: '您觉得冷吗？' },
        { standardAsk: '您还有什么想说的吗？', localAsk: '您还有想说的吗？' }
      ],

      confusions: [
        { heard: '在', shouldBe: '再', note: '同音字' },
        { heard: '的', shouldBe: '得', note: '轻声同音，补语"得"常被写成"的"' },
        { heard: '地', shouldBe: '的', note: '轻声同音，状语"地"常被写成"的"' },
        { heard: '做', shouldBe: '作', note: '同音字' },
        { heard: '象', shouldBe: '像', note: '同音字' },
        { heard: '带', shouldBe: '戴', note: '同音字' },
        { heard: '帐', shouldBe: '账', note: '同音字' },
        { heard: '那', shouldBe: '哪', note: '同音字，问句里容易混淆' },
        { heard: '须', shouldBe: '需', note: '同音字' },
        { heard: '两', shouldBe: '俩', note: '"俩"是"两个"的口语合音' },
        { heard: '干吗', shouldBe: '干嘛', note: '口语常写作"干嘛"' },
        { heard: '那会', shouldBe: '那会儿', note: '儿化音容易丢' }
      ],

      flavor: ['行', '挺好', '那会儿', '这会儿', '大伙儿', '一辈子', '头一回', '慢慢儿']
    }
  ],

  // 家人协助纠错时的界面文案
  assistPrompts: [
    '这句我没听准，您帮着改一下',
    '转写出来的字可能不对，麻烦您核对',
    '老人说的方言词，请您标出普通话',
    '下面有几个候选词，对的直接点一下',
    '听不清的地方，可以播放原音再听一遍',
    '不认识的字可以先跳过，不影响整篇传记',
    '改完记得点保存，谢谢您',
    '您比软件更懂老人的话，请多担待',
    '每改对一处，后辈读到的传记就更准确',
    '不用全改，只改您觉得不对的地方就行',
    '拿不准的词宁可保留原样，别乱猜',
    '可以问问家里其他人，一起核对'
  ],

  // 全国普遍存在的听写错误类型
  commonConfusions: [
    { kind: '前后鼻音', example: '陈 / 程', note: 'in/ing、en/eng 不分，北方很多地方都有' },
    { kind: '前后鼻音', example: '民 / 明', note: '' },
    { kind: '前后鼻音', example: '森 / 生', note: '' },
    { kind: '平翘舌', example: '四 / 是', note: 'zh/ch/sh 与 z/c/s 不分' },
    { kind: '平翘舌', example: '三 / 山', note: '' },
    { kind: 'n/l 不分', example: '男 / 兰', note: '多见于西南和部分北方地区' },
    { kind: 'n/l 不分', example: '牛 / 刘', note: '' },
    { kind: 'h/f 不分', example: '湖 / 福', note: '多见于湖南、湖北、四川等地' },
    { kind: 'r/y 不分', example: '人 / 银', note: '北方部分地区 r 声母读成 y' },
    { kind: 'r/y 不分', example: '热 / 夜', note: '' },
    { kind: '同音字', example: '在 / 再', note: '同音，听写容易选错字' },
    { kind: '同音字', example: '做 / 作', note: '' },
    { kind: '同音字', example: '像 / 象', note: '' },
    { kind: '同音字', example: '带 / 戴', note: '' },
    { kind: '轻声', example: '的 / 地 / 得', note: '轻声字同音，容易混' },
    { kind: '儿化音', example: '哪儿 / 那儿', note: '儿化音容易听错' },
    { kind: '语气词', example: '吗 / 嘛', note: '语气词听写容易混' },
    { kind: '量词', example: '俩 / 两', note: '' }
  ]
};
